<h3><?=i18n::tr('Branch provisions internet accounting')?></h3>

<form method="post" action="?section=<?=CalculationController::BRANCH_NET_SECTION_ID?>" id="formUsersFilter">
  <input type="hidden" name="form-submited" value="1"/>
  <?=$this->filter?>
  <div class="actions">
    <?=$this->render('calculation/export.phtml')?>
  </div>

  <table class='table-list width-100'>
    <?=$this->tHead?>
    <?=$this->tBody?>
  </table>
</form>