<div id="exportButtons">
	<input
	  type="submit"
	  name="export"
	  value="<?=i18n::tr('Export to PDF')?>"/>
	<input
	  type="submit"
	  name="exportCSV"
	  value="<?=i18n::tr('Export to CSV')?>"/>
	<input
	  type="submit"
	  name="exportKb"
	  value="<?=i18n::tr('Export KB')?>"/>
</div>
<script type="text/javascript">
	$(function() {
		$('#exportButtons input').click(function (){
			if ($('input.row-selector:checked').size() === 0) {
				alert('<?= i18n::tr('Choose some branch(es).') ?>');
				return false;
			}
		});
	});
</script>