<?=I18n::tr('new_branch_provider_registration')?>

=======================================================


<?=I18n::tr('company_info')?>

-------------------------------------------------------
<?=I18n::tr('company_name')?>: <?=$this->companyName?>

<?=I18n::tr('company_address')?>: <?=$this->companyAddress?>

<?=I18n::tr('company_representative')?>: <?=$this->companyRepresentative?>

<?=I18n::tr('company_phone')?>: <?=$this->companyPhone?>

<?=I18n::tr('company_mobile')?>: <?=$this->companyMobile?>

<?=I18n::tr('company_fax')?>: <?=$this->companyFax?>

<?=I18n::tr('company_email')?>: <?=$this->companyEmail?>

<?=I18n::tr('company_ic')?>: <?=$this->companyDic?>

<?=I18n::tr('company_dic')?>: <?=$this->companyIc?>



<?=I18n::tr('location_info')?>

-------------------------------------------------------
<?=I18n::tr('location_name')?>: <?=$this->locationName?>

<?=I18n::tr('location_address')?>: <?=$this->locationAddress?>

<?=I18n::tr('location_type')?>: <?=$this->locationType?>

<?=I18n::tr('location_phone')?>: <?=$this->locationPhone?>

<?=I18n::tr('location_mobile')?>: <?=$this->locationMobile?>

<?=I18n::tr('location_fax')?>: <?=$this->locationFax?>

<?=I18n::tr('location_email')?>: <?=$this->locationEmail?>



<?=I18n::tr('opening_hours')?>

-------------------------------------------------------
<?=I18n::tr('monday')?>: <?=$this->openingHoursMon?>

<?=I18n::tr('tuesday')?>: <?=$this->openingHoursTue?>

<?=I18n::tr('wednesday')?>: <?=$this->openingHoursWed?>

<?=I18n::tr('thursday')?>: <?=$this->openingHoursThu?>

<?=I18n::tr('friday')?>: <?=$this->openingHoursFri?>

<?=I18n::tr('saturday')?>: <?=$this->openingHoursSat?>

<?=I18n::tr('sunday')?>: <?=$this->openingHoursSun?>

