<?=I18n::tr('new_branch_provider_registration')?><br />
=======================================================

<table width="640" cellpadding="0" cellspacing="0" style="color: #8E8D8D; font-size: 11px; font-family: arial, verdana, helvetica, sans-serif; background: url('<?=PROTOCOL?><?=WEBHOSTL3?>/images/email_body_bg.png'); padding: 20px">
	<tbody>
		<tr>
			<td colspan="2"><h3><?=I18n::tr('company_info')?></h3></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_name')?></th>
			<td><?=$this->companyName?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_address')?></th>
			<td><?=$this->companyAddress?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_representative')?></th>
			<td><?=$this->companyRepresentative?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_phone')?></th>
			<td><?=$this->companyPhone?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_mobile')?></th>
			<td><?=$this->companyMobile?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_fax')?></th>
			<td><?=$this->companyFax?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_email')?></th>
			<td><?=$this->companyEmail?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_ic')?></th>
			<td><?=$this->companyDic?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('company_dic')?></th>
			<td><?=$this->companyIc?></td>
		</tr>


		<tr>
			<td colspan="2"><h3><?=I18n::tr('location_info')?></h3></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_name')?></th>
			<td><?=$this->locationName?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_address')?></th>
			<td><?=$this->locationAddress?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_type')?></th>
			<td><?=$this->locationType?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_phone')?></th>
			<td><?=$this->locationPhone?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_mobile')?></th>
			<td><?=$this->locationMobile?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_fax')?></th>
			<td><?=$this->locationFax?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('location_email')?></th>
			<td><?=$this->locationEmail?></td>
		</tr>


		<tr>
			<td colspan="2"><h3><?=I18n::tr('opening_hours')?></h3></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('monday')?></th>
			<td><?=$this->openingHoursMon?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('tuesday')?></th>
			<td><?=$this->openingHoursTue?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('wednesday')?></th>
			<td><?=$this->openingHoursWed?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('thursday')?></th>
			<td><?=$this->openingHoursThu?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('friday')?></th>
			<td><?=$this->openingHoursFri?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('saturday')?></th>
			<td><?=$this->openingHoursSat?></td>
		</tr>
		<tr>
			<th style="text-align: left"><?=I18n::tr('sunday')?></th>
			<td><?=$this->openingHoursSun?></td>
		</tr>
	</tbody>
</table>