<?=$this->feedbackMsg?>
<div class="actions">
	<button onclick="editParameterUser()"><?=i18n::tr('edit')?></button>
</div>
<table class="table-detail">

	<tr>
		<th class="header" colspan="4">
			<?=i18n::tr('user_parameter_defaults')?>
		</th>
	</tr>
	<?php foreach($this->userParameters as $param):?>
		<tr>
			<th><?=$param['name']?></th>
			<td><?=strlen($param['value']) > 50 ? substr($param['value'], 0, 50).'...' : $param['value']?></td>
			<td><?=($param['isEditable'] == 1 ? I18n::tr('editable') : I18n::tr('not_editable'))?></td>
			<td><?=$param['description']?></td>
		</tr>
	<?php endforeach?>

</table>
