import os, time, logging
from datetime import timedelta
import itertools

from database import Database
from worker import Worker
from form import Form
from request import Request
from report import report_generators
from report.template_filler import TemplateFiller


class Processor:
    def __init__(self, stringsloader):
        self.db = Database()
        self.stringsloader = stringsloader
        self.log = logging.getLogger('main')
        self.idgen = itertools.count()
        self.forms = {}


    def loadForms(self, path):
        if path is None:
            return
        for fname in sorted(os.listdir(path)):
            if fname.endswith('.frm'):
                # load
                f = Form()
                f.load(path+'/'+fname)
                doctype = f.name.lower()
                self.forms[doctype] = f
                # add db func
                if f.query:
                    self.db.registerQueryFunc(doctype, f.query)
                # add report generator
                report_generators[doctype] = TemplateFiller(f)


    def newRequest(self):
        req = Request()
        req.documenttype_enum += self.forms.keys()
        return req


    def listGroups(self):
        return self.db.queryGroups()


    def listActions(self, group=3):
        sports = self.db.queryAllSports()
        actions = self.db.queryAllEvents(True)
#        rows = self.db.queryActions(group)
#        last_sport = None
#        sports = []
#        actions = {}
#        for row in rows:
#            sport, sport_name, action, action_name = row
#            if sport != last_sport:
#                last_sport = sport
#                sports += [(sport, sport_name)]
#                actions[sport] = []
#            actions[sport] += [(action, action_name)]
        return sports, actions

    def listBetTypes(self):
        return self.db.queryAllBetTypes()

    def listStatsDates(self):
        rows = self.db.queryStatsDates()
        return [row[0].strftime('%F') for row in rows]


    def getStats(self, date=None):
        if date:
            try:
                time.strptime(date, '%Y-%m-%d')
            except ValueError:
                return ['Error', []]
        rows = self.db.queryStats(date)
        if not rows:
            return ['No data', []]
        statsdate = rows[0][0].strftime('%Y-%m-%d')
        res = []
        prevtime = None
        for row in rows:
            row = list(row)
            # add zeros where rows are missing
            if prevtime:
                nexttime = prevtime + timedelta(minutes=10)
                while row[0] > nexttime:
                    res += [[nexttime.strftime('%H:%M'), 0, 0, 0, 0, 0]]
                    nexttime = nexttime + timedelta(minutes=10)
            prevtime = row[0]
            row[0] = row[0].strftime('%H:%M')
            # append to result
            res += [row]
        return [statsdate, res]


    def updateStation(self, req):
        if not req.stationid:
            return
        st = self.db.queryStation(req.stationid)
        req.stationname = st['stanice']
        req.stationmid = st['mid']
        req.centreid = st['sberna']
        req.group = st['id_skupina']


    def updateUser(self, req):
        if not req.userid:
            return
        user = self.db.queryUser(req.userid)
        req.username = user['uzivatel']


    def checkCache(self, req):
        rows = self.db.queryDocumentCache(req)

        states = [r['status'] for r in rows]

        def getrow(st): return [r for r in rows if r['status'] == st][0]

        # ok
        if 0 in states:
            row = getrow(0)
            doc = (row['id_tiskopis'], row['pocet_stran'])
            return (doc, False, None) # id, wait, regen

        # regenerate
        if 3 in states:
            regen = getrow(3)['id_tiskopis']
            if 1 in states:
                row = getrow(1)
                doc = (row['id_tiskopis'], row['pocet_stran'])
                wait = False
            else:
                doc = None
                wait = True
            return (doc, wait, regen)

        # old exists, new is generated by other - just return old
        if 1 in states and 2 in states:
            row = getrow(1)
            doc = (row['id_tiskopis'], row['pocet_stran'])
            return (doc, False, None) # id, wait, regen

        # generated by other, wait
        if 2 in states:
            row = getrow(2)
            doc = (row['id_tiskopis'], None)
            return (doc, True, None)

        return None


    def processRequest(self, req, clientaddr):
        tid = self.idgen.next()
        self.log.info('[%d] Request %r from %s', tid, req.documenttype, clientaddr[0])

        self.updateStation(req)
        self.updateUser(req)

        if 'nocache' in req.debug:
            doc, wait, regen = None, True, 0
        else:
            doc, wait, regen = self.checkCache(req)

        result = {}
        output = None
        worker = None

        if doc and not wait:
            self.log.info('[%d] Found in cache: %d', tid, doc[0])
            output = (doc[0], req.outputformat, doc[1])
            result['fromcache'] = True

        if not regen is None:
            # run worker
            self.log.info('[%d] Running worker: %d', tid, regen)

            strings = self.stringsloader.getStrings(req.documenttype)
            worker = Worker(req, regen, self.db, strings)
            worker.start()

            # should we wait?
            if wait:
                self.log.info('[%d] Waiting for worker', tid)
                worker.join()
                self.log.info('[%d] Done', tid)
                result.update( worker.result )

        # wait for documents generated from other threads
        if doc and wait:
            # simple database polling
            self.log.info('[%d] Waiting for other thread: %d', tid, doc[0])
            ready = None
            while not ready:
                ready, pcount = self.fb.checkDocument(doc[0])
                time.sleep(0.5)
            output = (doc[0], req.outputformat, pcount)

        if 'parameters' in req.debug:
            result['parameters'] = req.check()

        if output:
            result['output'] = output

        return result


