<div id="right">
	<h2 class="boxheader"><?= $this->trans('transactions') ?></h2>
		<form method="get" action="<?= $this->UrlSet(50) ?>" id="formUsersFilter">
			<?= $this->filter ?>
			<div class="contentbox">
				<?php if (!empty($this->layout()->data)) : ?>
						<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th class="id"><?= $this->trans('id') ?></th>
									<th class="name"><?= $this->trans('transactions_type') ?></th>
									<th class="value" style="text-align: right !important;"><?= $this->trans('transactions_value') ?></th>
									<th class="status" style="text-align: right !important;"><?= $this->trans('transactions_status') ?></th>
									<th class="value"  style="text-align: right !important;"><?= $this->trans('transactions_time') ?></th>
									<th class="value"  style="text-align: right !important;"><?= $this->trans('transactions_balance') ?></th>
								</tr>
							</thead>
							<?= $this->tbody ?>
						</table>
				<?php else : ?>
					<?= It6_FeedbackMsg::printWarning('no-data'); ?>
				<?php endif; ?>
				<?= $this->paginator ?>
			</div>
		</form>
	<script type="text/javascript">
		// datepicker dočasně, pak přidat do komponenty
		$(document).ready(function() {
			$('.calendar-icon').each(function(i, elem){
				var id = $(elem).prev().attr('id');
				$(elem).wrap('<label for="'+id+'"></label>');
			});
			$('.dateOnly').datepicker({
				'dateFormat': 'dd.mm.yy'
			});
		});
	</script>
</div>

<?= $this->render('myaccount/user-profile-left-col.phtml'); ?>