<h3><?=i18n::tr('cash_overview')?></h3>

<form id="cashOverview" method="post" action="?section=<?=ListingsController::CASH_OVERVIEW_SECTION_ID?>" id="formUsersFilter">
  <?=$this->filter?>
  <div class="actions">
    <input
      type="submit"
      name="export"
      onclick="$('div.table-filter input:text, div.table-filter select').val(''); return false;"
      value="<?=i18n::tr('Reset_filter')?>"/>
    <?php if($this->showExport == true):?>
    <input
      type="submit"
      name="export"
      value="<?=i18n::tr('Export')?>"/>
      <?php endif;?>
  </div>
  <?=$this->paginator?>

  <table class='table-list width-100'>
    <?=$this->tHeadSum?>
    <?=$this->tBodySum?>
    <?=$this->tHead?>
    <?=$this->tBody?>
  </table>
</form>