<?=$this->feedbackMsg?>

<div class="actions">
	<button onclick="loadGeneric(<?=$this->viewSectionId?>, 'branch-host', { branchId : $('#branchId').val() })"><?=i18n::tr('List Hosts')?></button>
	<button onclick="hideDetail('branch-container')"><?=i18n::tr('Close Detail')?></button>
</div>

<?php $exists =  (count($this->hosts) > 0); ?>
<?php echo $this->feedbackMsg; ?>

<?php echo $this->form; ?>


<?php include('host-list.phtml'); ?>

