<table width="640" cellpadding="0" cellspacing="0" style="color: #8E8D8D; font-size: 11px; font-family: arial, verdana, helvetica, sans-serif; background: url('<?=PROTOCOL?><?=WEBHOSTL3?>/images/email_body_bg.png'); padding: 20px">
	<tbody>
		<tr>
			<td colspan="2">
				<h1 style="color: #F4CA6D; font-size: 19px; margin: 15px 0;">
					<?=I18n::tr('bets_results_canceled')?>
				</h1>
			</td>
		</tr>
		<tr>
			<td style="padding: 10px 0 5px 0">
				<b><?=I18n::tr('following_bet_canceled')?>:</b>
			</td>
		</tr>
		<tr>
			<td>
				<?=$this->betInfo['sport']?> - <?=$this->betInfo['region']?> - <?=$this->betInfo['event']?>: <?=$this->betInfo['type']?> -&gt; <?=$this->betInfo['text']?>
			</td>
		</tr>

		<tr>
			<td style="padding: 10px 0 5px 0">
				<b><?=I18n::tr('following_tickets_affected')?>:</b>
			</td>
		</tr>
		<?php foreach ($this->tickets as $ticketId => $ticket) : ?>
			<tr>
				<td>
					#<?=$ticket['handle']?> (<?=I18n::tr($ticket['type'])?>): -<?=$ticket['loss']?> <?=$this->currencyName?>
					(<?=I18n::tr('created_at')?>: <?=$ticket['createdAt']?>)
				</td>
			</tr>
		<?php endforeach?>
	</tbody>
</table>