<?php
			if (!empty($this->tickets)) : ?>
			<a href="<?= $this->UrlSet(100) ?>"><img src="/images/noglow_tablet.png" class="corvette" /></a>
                            <img src="/images/ticket-line-separator-small.png" class="sep-marg" />
				<?php $i = 0; foreach($this->tickets as $data) : ++$i ?>
					<div class="user">
						<div class="img">
							<table>
								<tr>
									<td>
										<img src="/images/avatar.png" alt="<?= $this->trans($this->game['gameName']) ?>" />
									</td>
								</tr>
							</table>
						</div>
						<div class="txt">
							<h4><?= $data['nick'] ?></h4>
                                                        <span class="gray morespace"><?= ucfirst($this->trans($this->evaluationName)) ?>:</span>
							<span class="white"><?= $data['rate'] ?></span><br />
                                                        <span class="gray"><?= $this->trans('totalWin') ?>:</span>
							<span class="white"><?= $this->NumberFormat($data['won']) ?> <?= $data['currencyName'] ?></span>
						</div>
                                                <img src="/images/odrazka.png" class="ticket_arrow" />
						<a href="<?= $this->UrlSet(95)?>g/<?= $this->game['gameId'] ?>/t/<?= $i ?>" class="button-gray">
							<?= $this->trans('ticket_game_ticket_info') ?>
						</a>
					</div>
				<?php endforeach?>
			<?php else : ?>
				<span class="white"><?= $this->trans('no_tickets_in_game') ?></span>
			<?php endif?>
