<?=$this->feedbackMsg?>

<div class="actions">
	<button onclick="loadGeneric(<?=$this->viewSectionId?>, 'user-profile', { userId : <?=$this->userId?> })"><?=i18n::tr('View')?></button>
	<button onclick="hideDetail('user-container')"><?=i18n::tr('Close Detail')?></button>
</div>

<div><?= $this->user['firstName'] ?> <?= $this->user['lastName'] ?> (<?= $this->user['username'] ?>)</div>
<?=$this->userProfileForm?>
