<h3><?=i18n::tr('parameters_settings')?></h3>

<?=$this->feedbackMsg?>

<ul class="idTabs">
	<li><a class="selected" href="#parameters-settings" onClick="loadTabGeneric(356, 'parameters-settings', { id : $('#id').val() })"><?=i18n::tr('parameters')?></a></li>
	<li><a href="#data-settings" onClick="loadTabGeneric(359, { id : $('#id').val() })"><?=i18n::tr('data_typ')?></a></li>
</ul>



<div id="data-settings-container" class="tab-container hidden">
	<input type="hidden" class="tabsLoaded" id="data-settings-main-loaded" value="0" />
	<input type="hidden" class="tabsLoaded" id="data-settings-event-loaded" value="0" />

	<input type="hidden" name="paramId" id="paramId" value="">

	<div id="data-settings-main" class="tab" style="display: none;">
	</div>
</div>

<div id="list">

	<form method="post" action="?section=<?=$this->indexSectionId?>" id="formParamsFilter">
		<div class="actions">
			<?php if($this->callcenterLogged === false):?>
			<input type="button" onClick="insertParam()" class="input"  name="insert_new" value="<?=i18n::tr('new_param')?>" />
			<?php endif;?>
		</div>
		<?=$this->filter?>
		<?=$this->paginator?>

		<table class='table-list width-100'>
			<?=$this->tHead?>
			<?=$this->tBody?>
		</table>
	</form>
</div>

<?php if (!empty($_GET['id'])): ?>
<script>
	viewParamDetail(<?=intval($_GET['id'])?>);
</script>
<?endif;?>
