	<div class="clearfix"></div>

	<footer id="footer">
		<div id="true-footer">
			<div class="wrapper">
				<nav id="footer-nav">
					<ul class="nav navbar-nav">
						<li><a href="#">Aktuality</a></li>
						<li><a href="#">Mobilní verze</a></li>
						<li><a href="#">Partnerství</a></li>
						<li><a href="#">Zaměstnání</a></li>
						<li><a href="#">Sportbets</a></li>
						<li><a href="livebets.php">Livebets</a></li>
						<li><a href="#">Casino</a></li>
						<li><a href="#">Poker</a></li>
					</ul>
				</nav>
				<p>Přístupem, pokračovaným užíváním nebo prohlížením této stránky souhlasíte, že využíváme určitých cookies pro zdokonalení služeb pro naše zákazníky. Náš server používá výhradně cookies, které vylepšují chod stránky a nenarušují vaše soukromí. Více informací o využití, spracování a případném zakázání cookies můžete najít zde.</p>
				<p class="bottom">NAME (licence: XXXXXXXXX) je licencována britskou licenční radou Gambling Commission.<br>Copyright &copy; 2014 NAME. Design by <a href="http://www.wda.cz">WDA Czech, s.r.o.</a> All rights reserved.</p>
			</div>
		</div>
	</footer>
	
	<a class="scrollup" href="#"><i class="fa fa-chevron-circle-up"></i></a>
	
	<div id="welcome-bg" class="animate-in slow-mo" data-anim-type="fade-in"></div>

<?php if(false){ ?>
<div id="footer">
  <div class="fmenu">
    <div class="wrapper">
      <div class="left">
        <ul>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(29); ?>">
                <?=$this->trans('about_company'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(20); ?>">
                <?=$this->trans('game-rules'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(30); ?>">
                <?=$this->trans('cooperation'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(23); ?>">
                <?=$this->trans('branches'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(26); ?>">
                <?=$this->trans('bonus'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(5000); ?>">
                <?=$this->trans('faq'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(5001); ?>">
                <?=$this->trans('customer_service'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
        </ul>
      </div>
      <div class="right">
        <span class="time" id="dayC"></span>&nbsp;
        <span class="time" id="hoursC"></span>
      </div>
    </div>
  </div>
  <div class="fmenu icons">
    <div class="wrapper">
      <div class="left">
        <a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-visa.png" alt="icon-visa" /></a>
        <a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-mastercard.png" alt="icon-mastercard" /></a>
        <a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-transfer.png" alt="icon-transfer" /></a>
       </div>
      <div class="right">
        <a href="https://www.facebook.com/BetService" target="_blank">
          <img src="/images/icon-facebook.png" alt="facebook_betservice" />
        </a>
      </div>
    </div>
  </div>
  <div id="copy">
    <div class="wrapper">
      <div class="left">
        &nbsp;<span class="eighteen">18+</span><?=$this->trans('prove18'); ?>
        <span> | </span>
        <?=$this->trans('bad_habbit'); ?>
      </div>
    </div>
  </div>
   <div class="fmenu">
    <div class="wrapper">
      <div class="left">
        <ul>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="/pdf/newspapers/<?=$this->newspapersFileName?>">
                <?=$this->trans('vt_newspapers'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
        <a href="/offer.php?DateFilter=Today&amp;Category=1">
          <?=$this->trans('offer-today'); ?>
        </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
        <a href="/offer.php?DateFilter=Today&amp;Category=3">
          <?=$this->trans('offer-today-all'); ?>
        </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
        <a href="/offer.php?DateFilter=All&amp;Category=3">
          <?=$this->trans('offer-all'); ?>
        </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?= $this->UrlSet(100) ?>"><?=$this->trans('competions');?></a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
        </ul>
      </div>
      <div class="right">
      <span class="time"><?=$this->trans('rights'); ?></span>
      </div>
    </div>
  </div>
</div>
<?php } ?>