<?=$this->feedbackMsg?>

<?php if ($this->affiliateBanner) : ?>

	<input name="affiliateBannerId" id="affiliateBannerId" type="hidden" value="<?=$this->affiliateBanner['affiliateBannerId']?>" />
	<div class="actions">
		<button onClick="editAffiliateBannerDetail(<?=$this->affiliateBanner['affiliateBannerId']?>)"><?=i18n::tr('edit')?></button>
		<button onclick="hideDetail('affiliate-banner-container')"><?=i18n::tr('close_detail')?></button>
	</div>

	<table class="table-detail">
		<tr>
			<th class="header" colspan="2"><?=i18n::tr('banner')?></th>
		</tr>
		<tr>
			<th><?=i18n::tr('Id')?></th>
			<td id="affiliate_banner_id"><?=$this->affiliateBanner['affiliateBannerId']?></td>
		</tr>
		<tr>
			<th><?=i18n::tr('article_title')?></th>
			<td><?=$this->affiliateBanner['imageTitle']?></td>
		</tr>
		<tr>
			<th><?=i18n::tr('file_name')?></th>
			<td id="name"><?=$this->affiliateBanner['fileName']?></td>
		</tr>
		<tr>
			<th>ALT</th>
			<td id="name"><?=$this->affiliateBanner['alt']?></td>
		</tr>
		<tr>
			<th><?=i18n::tr('type_open')?></th>
			<td><?=$this->affiliateBanner['target']?></td>
		</tr>
		<tr>
			<th><?=i18n::tr('valid_from')?></th>
			<td id="created"><?=$this->affiliateBanner['validFrom']?></td>
		</tr>
		<tr>
			<th><?=i18n::tr('valid_to')?></th>
			<td id="created"><?=$this->affiliateBanner['validTo']?></td>
		</tr>
	</table>

<?php endif; ?>