<?=$this->feedbackMsg?>

<div class="actions">
	<button onclick="hideDetail('branch-container')"><?=i18n::tr('Close Detail')?></button>
</div>

<?php $exists =  (count($this->users) > 0); ?>
<?php if(!$exists) : ?>
	<?=UiUtil::printWarnings(I18n::tr('warn_no_branch_users'));?></span>
<?php else: ?>
	<?php if($this->user) : ?>
		<table class="table-detail" >
			<tr>
				<th><?=i18n::tr('User ID')?></th>
				<td><?=$this->user['userId']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('nick_name')?></th>
				<td><?=$this->user['username']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Name')?></th>
				<td><?=$this->user['firstName']?> <?=$this->user['lastName']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Sex')?></th>
				<td><?=$this->user['sex']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Birth date')?></th>
				<td><?=It6_Date::fromDbAsDate($this->user['birthDate'])?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Phone')?></th>
				<td><?=$this->user['phone']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Address')?></th>
				<td><?=$this->user['street']?>, <?=$this->user['town']?>, <?=$this->user['zip']?>, <?=$this->user['countryId']?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Last login')?></th>
				<td><?=It6_Date::fromDbAsDate($this->user['lastLoginTime'])?></td>
			</tr>
			<tr>
				<th><?=i18n::tr('Registration date')?></th>
				<td><?=It6_Date::fromDbAsDate($this->user['registrationTime'])?></td>
			</tr>
		</table>
	<?php endif; ?>
<?php endif; ?>
<!-- seznam vsech uzivatelu na pobocce -->
<?php include('user-list.phtml'); ?>
