<div>
	<a 
		href="<?=isset($promo['url']) ? $promo['url'] : ''?>"
	   class="layer4"
	   <?=$promo['target'] == '_blank' ? 'onclick="window.open (this.href, \'child\'); return false"': ''?>
	>
		<div class="layer1">
			<h2>
				<?=isset($promo['title']) ? $promo['title'] : ''?>
				</span>
			</h2>
			<div class="text">
				<p>
					<?=isset($promo['text']) ? $promo['text'] : ''?>
				</p>
			</div>
		</div>
		<div class="layer2"></div>
		<div class="layer3">
			<img src="/images/gallery/<?=isset($promo['img']) ? $promo['img'] : ''?>" alt="img" />
		</div>
	</a>
</div>
