<div id="footer">
  <div class="fmenu">
    <div class="wrapper">
      <div class="left">
        <ul>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(29); ?>">
                <?=$this->trans('about_company'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(20); ?>">
                <?=$this->trans('game-rules'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(30); ?>">
                <?=$this->trans('cooperation'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(23); ?>">
                <?=$this->trans('branches'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(26); ?>">
                <?=$this->trans('bonus'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(5000); ?>">
                <?=$this->trans('faq'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
          <li>
            <div class="cl"></div>
            <div class="cc">
              <a href="<?=$this->UrlSet(5001); ?>">
                <?=$this->trans('customer_service'); ?>
              </a>
            </div>
            <div class="cr"></div>
            <span>|</span>
          </li>
        </ul>
      </div>
      <div class="right">
        <span class="time" id="dayC"></span>&nbsp;
        <span class="time" id="hoursC"></span>
      </div>
    </div>
  </div>
  <div class="fmenu icons">
    <div class="wrapper">
      <div class="left">
      	<a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-visa.png" alt="icon-visa" /></a>
        <a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-mastercard.png" alt="icon-mastercard" /></a>
        <a href="<?=$this->UrlSet(21)?>"><img src="/images/icon-transfer.png" alt="icon-transfer" /></a>
       </div>
      <div class="right">
        <!--<a href="https://www.facebook.com/BetService" target="_blank">
          <img src="/images/icon-facebook.png" alt="facebook_betservice" />
        </a>-->
      </div>
    </div>
  </div>
  <div id="copy">
    <div class="wrapper">
      <div class="left">
        <span class="eighteen">18+</span><?=$this->trans('prove18'); ?>
      </div>
      <div class="right">
        <a href="/pdf/newspapers/<?=$this->newspapersFileName?>">
          <?=$this->trans('vt_newspapers'); ?>
        </a>
        <span> | </span>
        <a href="/offer.php?DateFilter=Today&amp;Category=1">
          <?=$this->trans('offer-today'); ?>
        </a>
        <span> | </span>
        <a href="/offer.php?DateFilter=Today&amp;Category=3">
          <?=$this->trans('offer-today-all'); ?>
        </a>
        <span> | </span>
        <a href="/offer.php?DateFilter=All&amp;Category=3">
          <?=$this->trans('offer-all'); ?>
        </a>
        <span> | </span>
        <a href="javascript:window.print();">
          <?=$this->trans('print'); ?>
        </a>
        <span> | </span>
        <a href="<?=$this->UrlSet(31); ?>" class="rss">RSS</a>
        <span> | </span>
        <span><?=$this->trans('rights'); ?></span>
      </div>
    </div>
  </div>
</div>