<script type="text/javascript">
/*
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26543427-1']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  
  _gaq.push( [ '_clearOrganic' ]);
  _gaq.push( [ '_addOrganic', "seznam.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "seznam.cz", "w" ]);
  _gaq.push( [ '_addOrganic', "centrum.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "atlas.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "volny.cz", "search" ]);
  _gaq.push( [ '_addOrganic', "jyxo.1188.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "1188.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "jyxo.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "tiscali.cz", "query" ]);
  _gaq.push( [ '_addOrganic', "zoohoo.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "mapy.cz", "ssq" ]);
  _gaq.push( [ '_addOrganic', "1.cz", "q" ]);
  _gaq.push( [ '_addOrganic', "najdi.si", "q" ]);
  
  _gaq.push(<?= empty($this->googleAnalyticsTracking) ? "['_trackPageview']" : $this->googleAnalyticsTracking ?>);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
*/
</script>

<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0010/5191.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
