<h3 class="boxheader"><?= $this->trans('timefilter_menu_header') ?></h3>
<div class="contentbox small-padding">
	<form class="form-inline" role="form">
		<?php
		$openUrl = $this->menu->getOpenUrl();
		if (isset($openUrl['sport']) && $openUrl['sport'] > 0) {
			$quickFilterLinkBase = $this->urlSet(2).$this->menu->getOpenPath().'/';
		} else {
			$quickFilterLinkBase = $this->urlSet(2);
		}
		?>

		<?php
		$checked = $highlight = '';
		if ($this->all) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><a href="<?= $this->urlSet(2) . '?all' ?>" id="all"><label><input type="checkbox" <?=$checked?> id="all"><?= $this->trans('all_quick_offer') ?></label></a></div>
		
		<?php
		$checked = $highlight = '';
		if ($this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TODAY) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><a href="<?= $quickFilterLinkBase . '?today=1' ?>" id="today"><label><input type="checkbox" <?=$checked?> /><?= $this->trans('today_quick_offer') ?></label></a></div>
		
		<?php
		$checked = $highlight = '';
		if ($this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TOMOROW) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><a href="<?= $quickFilterLinkBase . '?tomorow=1' ?>" id="tomorow"><label><input type="checkbox" <?=$checked?> /><?= $this->trans('tomorow_quick_offer') ?></label></a></div>
	</form>
</div>
