<h3 class="boxheader"><?= $this->trans('timefilter_menu_header') ?></h3>
<div class="contentbox small-padding">
	<form class="form-inline" role="form">
		<?php
		$openUrl = $this->menu->getOpenUrl();
		if (isset($openUrl['sport']) && $openUrl['sport'] > 0) {
			$quickFilterLinkBase = $this->urlSet(2).$this->menu->getOpenPath().'/';
		} else {
			$quickFilterLinkBase = $this->urlSet(2);
		}

		$checked = $highlight = '';
		if ($this->all) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><a href="<?= $this->urlSet(2) . '?all' ?>" id="all"><input type="checkbox" <?=$checked?> id="all" onclick='window.location.assign("<?= $quickFilterLinkBase . '?all' ?>")' /><?= $this->trans('all_quick_offer') ?></a></div>
		
		<?php
		$checked = $highlight = '';
		if ($this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TODAY || $this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TODAY_AND_TOMOROW) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><input type="checkbox" <?=$checked?>  id="chktoday" onclick="todayFunction(true);" /><a id="today" href="javascript:void(0)" onclick="todayFunction(false);"><?= $this->trans('today_quick_offer') ?></a></div>
		
		<?php
		$checked = $highlight = '';
		if ($this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TOMOROW || $this->timeFilter == Models_Markets_MarketData::TIME_FILTER_TODAY_AND_TOMOROW) {
			$checked = "checked"; $highlight = "highlight";
		} ?>
		<div class="checkbox <?=$highlight ?>"><input type="checkbox" <?=$checked?>  id="chktomorow" onclick="tomorowFunction(true);" /><a id="tomorow" href="javascript:void(0)" onclick="tomorowFunction(false);"><?= $this->trans('tomorow_quick_offer') ?></a></div>
	</form>
</div>

<script type="text/javascript">
function todayFunction(fromCheckBox){
	if (!fromCheckBox) {
		location = "<?= $quickFilterLinkBase . '?today=1' ?>";
	} else {
		var location = "<?= $quickFilterLinkBase . '?all' ?>";
		if ($('#chktoday').is(':checked') && $('#chktomorow').is(':checked')) {
			location = "<?= $quickFilterLinkBase . '?todayAndTomorow=1' ?>";
		} else {
			if (!fromCheckBox) {
				location = "<?= $quickFilterLinkBase . '?today=1' ?>";
			} else {
				if (document.getElementById('chktoday').checked) {
					location = "<?= $quickFilterLinkBase . '?today=1' ?>";
				} else {
					if ($('#chktomorow').is(':checked')) {
						location = "<?= $quickFilterLinkBase . '?tomorow=1' ?>";
					} else {
						location = "<?= $quickFilterLinkBase . '?all' ?>";
					}
				}
			}
		}
	}
	window.location.assign(location);
}

function tomorowFunction(fromCheckBox){
	if (!fromCheckBox) {
		location = "<?= $quickFilterLinkBase . '?tomorow=1' ?>";
	} else {	
		var location = "<?= $quickFilterLinkBase . '?all' ?>";
		if ($('#chktoday').is(':checked') && $('#chktomorow').is(':checked')) {
			location = "<?= $quickFilterLinkBase . '?todayAndTomorow=1' ?>";
		} else {
			if (!fromCheckBox) {
				location = "<?= $quickFilterLinkBase . '?tomorow=1' ?>";
			} else {
				if (document.getElementById('chktomorow').checked) {
					location = "<?= $quickFilterLinkBase . '?tomorow=1' ?>";
				} else {
					if ($('#chktoday').is(':checked')) {
						location = "<?= $quickFilterLinkBase . '?today=1' ?>";				
					} else {
						location = "<?= $quickFilterLinkBase . '?all' ?>";
					}

				}
			}
		}
	}
	window.location.assign(location);
}
</script>
