<?php if ($this->pageCount) : ?>
	<div class="lister-navigation-post">
		
		<input type="hidden" value="<?=$this->current?>" name="paginator[pageNumCur]" />

		<!-- Previous page link -->
		<?php if (isset($this->previous)) : ?>
			<div class="page">
				<input type="submit" value="<" name="paginator[pagePrev]" class="arrow-left" />
			</div>
			<input type="hidden" value="<?=$this->previous?>" name="paginator[pageNumPrev]" />
		<?php else : ?>
			<!--<span class="disabled">Previous</span> -->
		<?php endif?>
		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<div class="page" >
					<input type="submit" value="<?=$page?>" name="paginator[pageNum]" />
				</div>
			<?php else : ?>
		<div class="page"><input disabled="disabled" class="active" type="submit" value="<?=$page?>"></div>
			<?php endif?>
		<?php endforeach?>

		<!-- Next page link -->
		<?php if (isset($this->next)) : ?>
			<input type="hidden" value="<?=$this->next?>" name="paginator[pageNumNext]" />
			<div class="page">
				<input type="submit" class="arrow-right" value=">" name="paginator[pageNext]" />
			</div>
		<?php else : ?>
			<!--<span class="disabled">Next</span>-->
		<?php endif?>
</div>

<?php endif?>
