<thead>
	<tr>
		<th class="w100" <?php if(isset($this->layout()->columns[0][2])) echo 'style="text-align:'.$this->layout()->columns[0][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[0][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[1][2])) echo 'style="text-align:'.$this->layout()->columns[1][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[1][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[2][2])) echo 'style="text-align:'.$this->layout()->columns[2][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[2][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[3][2])) echo 'style="text-align:'.$this->layout()->columns[3][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[3][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[4][2])) echo 'style="text-align:'.$this->layout()->columns[4][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[4][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[5][2])) echo 'style="text-align:'.$this->layout()->columns[5][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[5][0])?>
		</th>
		<th <?php if(isset($this->layout()->columns[6][2])) echo 'style="text-align:'.$this->layout()->columns[6][2].';"'; ?> >
			<?=$this->trans($this->layout()->columns[6][0])?>
		</th>
	</tr>
</thead>
