set foreign_key_checks=0;
TRUNCATE `vic_main`.`coupon_data_archive`;
TRUNCATE `vic_main`.`coupon_data`;
TRUNCATE `vic_main`.`coupon_sequence`;
TRUNCATE `vic_main`.`vyherci_sazky`;
TRUNCATE vic_main.`financial_transaction`;
TRUNCATE vic_main.financial_transaction_history;
TRUNCATE vic_main.financial_transaction_handle_sequence;
TRUNCATE vic_main.`point_transaction`;
TRUNCATE vic_main.ticket_kurz;
TRUNCATE vic_main.tickethash_ticket;
TRUNCATE vic_main.tickethash;
TRUNCATE vic_main.ticket_combination;
TRUNCATE vic_main.ticket;
TRUNCATE vic_main.ticket_live;
TRUNCATE vic_main.ticket_sequence;
TRUNCATE vic_main.ticket_statistics_cashflow;
TRUNCATE vic_main.ticket_statistics_payout;
update  vic_main.`uzivatel_im_data` set `zustatek`=0,`zetony`=0,`dluh`=0,`zustatek_bonus`=0;
UPDATE `vic_main`.`point_account` SET `balance`=0,`balance_get`=0,`balance_spend`=0,`balance_exchange`=0;
truncate vic_admin.log;
update vic_admin.host set balance=0;
set foreign_key_checks=1;
