<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
	<meta http-equiv="content-language" content="cs" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="503 page" />
	<title>Služba je dočasně nedostupná</title>
</head>
<body>
	<p><img src="/images/logo.png" alt="CompBet sázková kancelář" /></p>
	<h2>Omlouváme se, služba je dočasně nedostupná. Zkuste to později.</h2>
</body>
</html>
