<?php
/* $Id:$
* template with language tabs
* IN:
*    $tabs - instance of class LanguageTabs
*/

if (!isset($tabs))
	return;
$jsTabsParam = $tabs->getId();
$jsTabsParam = (empty($jsTabsParam) ? '' : ", '$jsTabsParam'");
?>
<div class="language-tabs">
<?php foreach ($tabs->getLanguages() as $lang) : $iso = $lang['iso']; ?>
  <a href="#" id="<?= $tabs->getLinkId($iso) ?>" onclick="javascript:activateLanguageTab('<?= $iso ?>'<?= $jsTabsParam ?>); return false;"><?= $lang['alt_text'] ?></a>
<?php endforeach; ?>
</div>
