<?php
/**
 * default TinyMCE template
 * IN:
 *    $target - query string for target elements, default is 'textarea.tinymce'
 */
if (empty($target)) {
	$target = 'textarea.tinymce';
}
if (empty($defLang)) {
	$defLang = It6_Models_Language::getDatabyField(DEFAULT_LANG, 'isoCode');
}
if (empty($defHeight)) {
	$defHeight = 500;
}
?>

<script type="text/javascript">
	$().ready(function() {
		$('<?= $target ?>').tinymce({
			// Location of TinyMCE script
			script_url : '/js/tinymce/jscripts/tiny_mce/tiny_mce.js?r=<?= RELEASE_REV ?>',

			// General options
			theme : "advanced",
			plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

			// Theme options
			theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
			theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen, gallery",
			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,

			// Example content CSS (should be your site CSS)
			content_css : "css/content.css?r=<?= RELEASE_REV ?>",

			// Drop lists for link/image/media/template dialogs
			template_external_list_url : "lists/template_list.js",
			external_link_list_url : "lists/link_list.js",
			external_image_list_url : "lists/image_list.js",
			media_external_list_url : "lists/media_list.js",
			
			convert_urls : false,

            theme_advanced_resizing_use_cookie : false,
            height : <?= $defHeight ?>,

			// Replace values for the template plugin
			template_replace_values : {
				username : "Some User",
				staffid : "991234"
			},
			setup : function(ed) {
				// Add a custom button
				ed.addButton('gallery', {
					title : 'Gallery',
					image : '_clip/image_aktivni.gif',
					onclick : function() {
						$(document.createElement('div')).attr('id', 'tmp_element');
						window.open('/galery.php?type=1&cbfunc=placeImage_<?=$defLang['isoCode']?>','','width=640,height=480,scrollbars=yes');
					}
				});
			}

		});
	});
	
	
	function placeImage_<?=$defLang['isoCode']?>(imageArr) {
		imgTag = '<img alt="' + imageArr['alt']['<?=$defLang['isoCode']?>'] + '" src="/images/gallery/' + imageArr['name'] + '" />';
		tinyMCE.activeEditor.selection.setContent(imgTag);
	}
</script>
