START TRANSACTION;

INSERT INTO `controller_convert` (`c_id`, `lang_id`, `parent_id`, `poradi`, `zobrazeno`, `cols`, `left_side`, `right_side`, `title`, `description`, `keywords`, `text`, `req_controller`, `req_action`, `real_controller`, `real_action`, `after_login`, `actionless`, `nonassoc_params`) VALUES
(116, 1, 0, 1000, 1, 3, NULL, NULL, 'Provozní doba', 'Informace o změnách provozní doby během vánočních svátků na pobočkách CompBet a.s. a o dostupnosti LIVE sázek.', 'provozní doba,dostupnost,vánoční svátky', '', 'provozni-doba', 'index', 'static-page', 'operating-time', 1, 0, 0);

INSERT INTO `static_page` (`page_id`, `page_name`, `lang_id`, `template`, `layout_id`, `visible`, `page_content`) VALUES
(49, 'operating-time', 1, 'index', 1, 1, '<style>table#oper_time {border-collapse: separate;border-spacing: 2px;width: 100%;margin-bottom: 10px;}table#oper_time td {background-color:#1a1a1a;}table#oper_time td:first-child {color: #d6b46a;font-weight: bold;text-align: center;}table#oper_time td:nth-child(2) {text-align: center;}table#oper_time td:nth-child(3) {padding-left: 20px;}</style><div class="content_block"><h2 style="color: #f1f2f2;">Vážené dámy, vážení pánové,</h2><p>rádi bychom Vás informovali o změnách provozní doby během vánočních svátků na pobočkách CompBet a.s. a o dostupnosti LIVE sázek.</p><p style="color: #d6b46a;"><b>Přejeme Vám všem radostné Vánoce!</b></p><div class="line_separator_top">&nbsp;</div><div class="inner_content"><h2 style="text-align: center;">PROVOZNÍ DOBA BĚHEM VÁNOČNÍCH SVÁTKŮ</h2><div class="clear">&nbsp;</div></div><div class="line_separator_bottom">&nbsp;</div><table id="oper_time"><tr><td>24. 12. 2013</td><td>00:01 - 15:00</td><td>Provoz poboček a internetového sázení - <b><span style="color: #d6b46a">LIVE SÁZKY MIMO PROVOZ</span></b></td></tr><tr><td>25. 12. 2013</td><td>06:00 - 15:00</td><td>Provoz poboček a internetového sázení - <b><span style="color: #d6b46a">LIVE SÁZKY MIMO PROVOZ</span></b></td></tr><tr><td>26. 12. 2013</td><td>06:00 - 24:00</td><td>Provoz poboček, internetového i LIVE sázení</td></tr><tr><td colspan="2">27. 12. 2013 - 30. 12. 2013</td><td style="text-align: left; padding-left: 20px;">Běžná provozní doba</td></tr><tr><td>31. 12. 2013</td><td>00:01 - 20:00</td><td>Provoz poboček a internetového sázení - <b><span style="color: #d6b46a">LIVE SÁZKY MIMO PROVOZ</span></b></td></tr><tr><td>01. 01. 2014</td><td>ZAVŘENO</td><td>ZAVŘENO</td></tr><tr><td>02. 01. 2014</td><td>06:00 - 24:00</td><td>Provoz poboček, internetového i LIVE sázení</td></tr></table></div>');

COMMIT;
