INSERT INTO `vic_main`.`database_patch`(`revision`, `not_reapplicable`, `note`) VALUES
 ('7814', 1, 'Altered table vic_main.sazky_result to have column for each possible score from BR (mantis:310)');


ALTER TABLE `vic_main`.`sazky_result`
 CHANGE COLUMN `ap` `ap` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
 ADD COLUMN `1q` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `ap`,
 ADD COLUMN `2q` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `1q`,
 ADD COLUMN `3q` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `2q`,
 ADD COLUMN `4q` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `3q`,
 ADD COLUMN `set1` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `4q`,
 ADD COLUMN `set2` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `set1`,
 ADD COLUMN `set3` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `set2`,
 ADD COLUMN `set4` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `set3`,
 ADD COLUMN `set5` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `set4`,
 ADD COLUMN `wo` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL  COMMENT 'walk over' AFTER `set5`,
 ADD COLUMN `c` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL  COMMENT 'cancelation result' AFTER `wo`;
