ALTER TABLE `vic_main`.`ticket` ADD `mp` DECIMAL NOT NULL DEFAULT '0',
ADD `mp_win` DECIMAL NOT NULL DEFAULT '0';

DROP VIEW `vic_main`.`ticket_pohled_connect`;
CREATE VIEW `vic_main`.`ticket_pohled_connect` AS 
SELECT `a`.`sazka_id` AS `sazka_id`,`a`.`live` AS `live`,`a`.`platna_do` AS `platna_do`,`d`.`stats` AS `stats`,`d`.`stats_user` AS `stats_user`,`d`.`user_id` AS `user_id`,`a`.`proplacena` AS `proplacena`,`a`.`typ_id` AS `typ_id`,`a`.`text` AS `text`,`a`.`vysledek` AS `vysledek`,`a`.`status` AS `status`,`a`.`udalost_id` AS `udalost_id`,`b`.`kurz` AS `kurz`,`b`.`platny_od` AS `platny_od`,`b`.`kurz_zmena` AS `kurz_zmena`,`b`.`sloupec_id` AS `sloupec_id`,`b`.`poradi` AS `poradi`,`c`.`ticket_sazka_zrusena` AS `ticket_sazka_zrusena`,`c`.`ticket_sazka_zrusil_bookmaker_id` AS `ticket_sazka_zrusil_bookmaker_id`,`c`.`ticket_sazka_duvod_zruseni` AS `ticket_sazka_duvod_zruseni`,`c`.`banker` AS `banker`,`c`.`group_id` AS `group_id`,`d`.`ticket_id` AS `ticket_id`,`d`.`handle` AS `ticket_handle`,`d`.`host_id` AS `ticket_branch_id`,`d`.`type` AS `type`,`d`.`win` AS `win`,`d`.`rate` AS `rate`,`d`.`win_real` AS `win_real`,`d`.`rate_real` AS `rate_real`,`d`.`free_bet_bonus` AS `free_bet_bonus`,`d`.`zalozen` AS `zalozen`,`d`.`vyplacen` AS `vyplacen`,`d`.`zruseno` AS `zruseno`,`d`.`zrusil_bookmaker_id` AS `zrusil_bookmaker_id`,`d`.`duvod_zruseni` AS `duvod_zruseni`,`d`.`castka` AS `castka`,`d`.`system` AS `system`,`d`.`coupon_id` AS `coupon_id`,`d`.`mail` AS `mail`,`d`.`group_count` AS `group_count`,`d`.`group_t` AS `group_t`,`d`.`vyplacen_date` AS `vyplacen_date`,`d`.`vyplacen_bookmaker_id` AS `vyplacen_bookmaker_id`,`d`.`collection_time` AS `collection_time`,`d`.`collection_host_id` AS `collection_host_id`,`d`.`forced_collection_host_id` AS `forced_collection_host_id`,`d`.`cash` AS `cash`,`d`.`point_type_id` AS `point_type_id`,`d`.`rate_advance` AS `rate_advance`,`d`.`forfeit` AS `forfeit`, `d`.`mp` AS `mp`, `d`.`mp_win` AS `mp_win`
FROM (`sazky` `a` join (`sazka_kurz` `b` join (`ticket_kurz` `c` join `ticket` `d` on((`c`.`ticket_id` = `d`.`ticket_id`))) on(((`b`.`sazka_id` = `c`.`sazka_id`) and (`b`.`sloupec_id` = `c`.`sloupec_id`)))) on((`a`.`sazka_id` = `b`.`sazka_id`)));

DROP VIEW `vic_main`.`ticket_pohled` ;
CREATE VIEW `vic_main`.`ticket_pohled` AS
SELECT `b`.`sazka_id` AS `sazka_id`,`b`.`live` AS `live`,`b`.`platna_do` AS `platna_do`,`b`.`user_id` AS `user_id`,`b`.`proplacena` AS `proplacena`,`b`.`typ_id` AS `typ_id`,`b`.`text` AS `text`,`b`.`vysledek` AS `vysledek`,`b`.`status` AS `status`,`b`.`udalost_id` AS `udalost_id`,`b`.`kurz` AS `kurz`,`b`.`platny_od` AS `platny_od`,`b`.`sloupec_id` AS `sloupec_id`,`b`.`poradi` AS `poradi`,`b`.`ticket_sazka_zrusena` AS `ticket_sazka_zrusena`,`b`.`ticket_sazka_zrusil_bookmaker_id` AS `ticket_sazka_zrusil_bookmaker_id`,`b`.`ticket_sazka_duvod_zruseni` AS `ticket_sazka_duvod_zruseni`,`b`.`ticket_id` AS `ticket_id`,`b`.`ticket_handle` AS `ticket_handle`,`b`.`ticket_branch_id` AS `ticket_branch_id`,`b`.`zalozen` AS `zalozen`,`b`.`vyplacen` AS `vyplacen`,`b`.`type` AS `type`,`b`.`win` AS `win`,`b`.`rate` AS `rate`,`b`.`win_real` AS `win_real`,`b`.`rate_real` AS `rate_real`,`b`.`zruseno` AS `zruseno`,`b`.`kurz_zmena` AS `kurz_zmena`,`b`.`zrusil_bookmaker_id` AS `zrusil_bookmaker_id`,`b`.`duvod_zruseni` AS `duvod_zruseni`,`b`.`castka` AS `castka`,`b`.`free_bet_bonus` AS `free_bet_bonus`,`b`.`system` AS `system`,`b`.`stats` AS `stats`,`b`.`stats_user` AS `stats_user`,`b`.`banker` AS `banker`,`b`.`coupon_id` AS `coupon_id`,`b`.`mail` AS `mail`,`b`.`group_count` AS `group_count`,`b`.`group_t` AS `group_t`,`b`.`group_id` AS `group_id`,`b`.`vyplacen_date` AS `vyplacen_date`,`b`.`vyplacen_bookmaker_id` AS `vyplacen_bookmaker_id`,`b`.`cash` AS `cash`,`b`.`collection_time` AS `collection_time`,`b`.`collection_host_id` AS `collection_host_id`,`b`.`forced_collection_host_id` AS `forced_collection_host_id`,`b`.`point_type_id` AS `point_type_id`,`b`.`rate_advance` AS `rate_advance`,`b`.`forfeit` AS `forfeit`, `b`.`mp` AS `mp`, `b`.`mp_win` AS `mp_win`
FROM `ticket_pohled_connect` `b` where (`b`.`platny_od` = (select max(`a`.`platny_od`) AS `maxi_platny_od` from `ticket_pohled_connect` `a` where ((`a`.`zalozen` >= `a`.`platny_od`) and (`a`.`sazka_id` = `b`.`sazka_id`) and (`a`.`ticket_id` = `b`.`ticket_id`)) group by `a`.`ticket_id`,`a`.`sazka_id`));

START TRANSACTION;

INSERT INTO `vic_main`.`financial_transaction_type`
	(`id`, `name`, `note`, `from`, `thru`, `to`, `need_confirm`, `late_deposit`, `debiting`, `account_type`, `low_limit`, `high_limit`, `has_fee`, `fee_fix`, `fee_rel`, `is_limit_editable`, `is_fee_editable`)
VALUES
	(29, 'branch.ticket.create-cash-mp', 'Manipulacni poplatek ze zalozeni tiketu na pobocce za penize. Anonimne i neanonymne.', '211', NULL, '602', 0, 0, 0, 'host', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(30, 'user.ticket.create-mp', 'Manipulacni poplatek ze zalozeni tiketu z uctu uzivatele (na pobocce i na internetu)', '324', NULL, '602', 0, 0, 0, 'user', NULL, '0.00', 'never', NULL, NULL, 0, 0),
	(31, 'branch.ticket.cancel-cash-mp', 'Strono manipulacniho poplatku tiketu zalozeneho na poboce za penize (anonymniho i neanonymniho)', '602', NULL, '211', 0, 0, 0, 'host', NULL, '0.00', 'never', NULL, NULL, 0, 0),
	(32, 'user.ticket.cancel-mp', 'Strono manipulacniho poplatku tiketu zalozeneho z uctu uzivatele (na pobocce i internetu)', '602', NULL, '324', 0, 0, 0, 'user', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(33, 'user.ticket.payout-mp', 'Vyherni manipulacni poplatek pri vyplaceni necash tiketu.', '548', '379', '324', 0, 0, 0, 'user', NULL, '0.00', 'never', NULL, NULL, 0, 0),
	(34, 'user.ticket.payout-cancel-mp', 'Zruseni vyherniho manipulacniho poplatku pri zruseni vyplaceni necash tiketu', '324', '379', '548', 0, 0, 1, 'user', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(35, 'other.ticket.collect-individual-mp', 'Vyherni manipulacni poplatek pri vyplate tiketu individualne v kancelari', '379', NULL, '211', 0, 0, 0, 'other', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(36, 'branch.ticket.collect-mp', 'Vyherni manipulacni poplatek pri vyplate tiketu v hotovosti na pobocce', '379', NULL, '211', 0, 0, 0, 'host', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(37, 'other.ticket.payout-cash-mp', 'Vyherni manipulacni poplatek pri oznaceni cash tiketu za vyhrany (nikoliv jeho vyplaceni na pobocce), tato transakce je jen pro ucetnictvi', '548', NULL, '379', 0, 0, 0, 'other', '0.00', NULL, 'never', NULL, NULL, 0, 0),
	(38, 'other.ticket.payout-cash-cancel-mp', 'Storno vyherniho manipulacniho poplatku pri zruseni ozanceni cash tiketu za vyhrany. (tato transakce je pouze pro ucetnictvi)', '379', NULL, '548', 0, 0, 1, 'other', NULL, '0.00', 'never', NULL, NULL, 0, 0),
	(39, 'other.ticket.forfeit-mp', 'Propadnuti vitezneho manipulacniho poplatku pri propadnuti nevyzvednute vyhry', '379', NULL, '648', 0, 0, 1, 'other', NULL, NULL, 'never', NULL, NULL, 0, 0);
	
COMMIT;
