start transaction;
set @a=(SELECT MAX(preklad_id) FROM vic_main.preklady);

INSERT INTO vic_main.preklady (`lang_id`, `index_pole`, `short_text`, `text`, `translate`, `preklad_id`) VALUES
(1, 'Accounting', '', 'Účetnictví', 0, @a + 1),
(2, 'Accounting', '', '', 0, @a + 1),
(16, 'Accounting', '', '', 0, @a + 1),
(1, 'Day book accounting', '', 'Účetní deník', 0, @a + 2),
(2, 'Day book accounting', '', '', 0, @a + 2),
(16, 'Day book accounting', '', '', 0, @a + 2),
(1, 'Branch provisions accounting', '', 'Provize poboček', 0, @a + 3),
(2, 'Branch provisions accounting', '', '', 0, @a + 3),
(16, 'Branch provisions accounting', '', '', 0, @a + 3),
(1, 'Balancing', '', 'Denní uzávěrky poboček', 0, @a + 7),
(2, 'Balancing', '', '', 0, @a + 7),
(16, 'Balancing', '', '', 0, @a + 7),
(1, 'Global Balancing', '', 'Celková denní uzávěrka', 0, @a + 8),
(2, 'Global Balancing', '', '', 0, @a + 8),
(16, 'Global Balancing', '', '', 0, @a + 8),
(1, 'Branch funding', '', 'Dotace/odvody poboček', 0, @a + 9),
(2, 'Branch funding', '', '', 0, @a + 9),
(16, 'Branch funding', '', '', 0, @a + 9),
(1, 'Cancel transaction', '', 'Storno transakce', 0, @a + 10),
(2, 'Cancel transaction', '', '', 0, @a + 10),
(16, 'Cancel transaction', '', '', 0, @a + 10),
(1, 'Point transactions', '', 'Bodové transakce', 0, @a + 11),
(2, 'Point transactions', '', '', 0, @a + 11),
(16, 'Point transactions', '', '', 0, @a + 11),
(1, 'Confirmations', '', 'Transakce ke schválení', 0, @a + 12),
(2, 'Confirmations', '', '', 0, @a + 12),
(16, 'Confirmations', '', '', 0, @a + 12),
(1, 'Predeposits', '', 'Transakce ke zpětnému potvrzení', 0, @a + 13),
(2, 'Predeposits', '', '', 0, @a + 13),
(16, 'Predeposits', '', '', 0, @a + 13),
(1, 'Global Parameters', '', 'Globální parametry', 0, @a + 14),
(2, 'Global Parameters', '', '', 0, @a + 14),
(16, 'Global Parameters', '', '', 0, @a + 14),
(1, 'Transaction types', '', 'Limity a poplatky za transakce', 0, @a + 15),
(2, 'Transaction types', '', '', 0, @a + 15),
(16, 'Transaction types', '', '', 0, @a + 15),
(1, 'Missing translations', '', 'Chybějící překlady', 0, @a + 16),
(2, 'Missing translations', '', '', 0, @a + 16),
(16, 'Missing translations', '', '', 0, @a + 16),
(1, 'Duplicate tickets', '', 'Duplikátní tikety', 0, @a + 17),
(2, 'Duplicate tickets', '', '', 0, @a + 17),
(16, 'Duplicate tickets', '', '', 0, @a + 17),
(1, 'Admins', '', 'Administrátoři', 0, @a + 18),
(2, 'Admins', '', '', 0, @a + 18),
(16, 'Admins', '', '', 0, @a + 18),
(1, 'Host dashboard', '', 'Panel pooček', 0, @a + 19),
(2, 'Host dashboard', '', '', 0, @a + 19),
(16, 'Host dashboard', '', '', 0, @a + 19),
(1, 'Branch management', '', 'Správa poboček', 0, @a + 20),
(2, 'Branch management', '', '', 0, @a + 20),
(16, 'Branch management', '', '', 0, @a + 20),
(1, 'Team', '', 'Týmy', 0, @a + 22),
(2, 'Team', '', '', 0, @a + 22),
(16, 'Team', '', '', 0, @a + 22),
(1, 'Approval Group', '', 'Limity pro schvalování', 0, @a + 23),
(2, 'Approval Group', '', '', 0, @a + 23),
(16, 'Approval Group', '', '', 0, @a + 23),
(1, 'Logs', '', 'Logy', 0, @a + 24),
(2, 'Logs', '', '', 0, @a + 24),
(16, 'Logs', '', '', 0, @a + 24),
(1, 'Statistics', '', 'Statistiky', 0, @a + 25),
(2, 'Statistics', '', '', 0, @a + 25),
(16, 'Statistics', '', '', 0, @a + 25),
(1, 'Branches/Hosts', '', 'Pobočky', 0, @a + 26),
(2, 'Branches/Hosts', '', '', 0, @a + 26),
(16, 'Branches/Hosts', '', '', 0, @a + 26),
(1, 'Welcome to BBAS', '', 'Vítej do BEWy!', 0, @a + 28),
(2, 'Welcome to BBAS', '', '', 0, @a + 28),
(16, 'Welcome to BBAS', '', '', 0, @a + 28),
(1, 'Description', '', 'Popis', 0, @a + 29),
(2, 'Description', '', '', 0, @a + 29),
(16, 'Description', '', '', 0, @a + 29),
(1, 'Account', '', 'Účet', 0, @a + 30),
(2, 'Account', '', '', 0, @a + 30),
(16, 'Account', '', '', 0, @a + 30),
(1, 'Date change', '', 'Datum změny', 1, @a + 31),
(2, 'Date change', '', '', 1, @a + 31),
(16, 'Date change', '', '', 1, @a + 31),
(1, 'Currency code', '', 'Kód měny', 1, @a + 32),
(2, 'Currency code', '', '', 1, @a + 32),
(16, 'Currency code', '', '', 1, @a + 32),
(1, 'Ticket id', '', 'č.tiketu', 1, @a + 34),
(2, 'Ticket id', '', '', 1, @a + 34),
(16, 'Ticket id', '', '', 1, @a + 34),
(1, 'user id', '', 'č.uživatele', 1, @a + 35),
(2, 'user id', '', '', 1, @a + 35),
(16, 'user id', '', '', 1, @a + 35),
(1, 'Variable symbol', '', 'Var. symbol', 0, @a + 36),
(2, 'Variable symbol', '', '', 1, @a + 36),
(16, 'Variable symbol', '', '', 0, @a + 36),
(1, 'in_need_of_funds', '', 'Pobočky co potřebují dotaci/odvod', 0, @a + 39),
(2, 'in_need_of_funds', '', '', 1, @a + 39),
(16, 'in_need_of_funds', '', '', 0, @a + 39),
(1, 'not_in_need_of_funds', '', 'Pobočky bez potřeby dotace/odvodu', 0, @a + 40),
(2, 'not_in_need_of_funds', '', '', 1, @a + 40),
(16, 'not_in_need_of_funds', '', '', 0, @a + 40),
(1, 'Show', '', 'Zobrazit', 1, @a + 41),
(2, 'Show', '', '', 1, @a + 41),
(16, 'Show', '', '', 1, @a + 41),
(1, 'recommended-deposit', '', 'Doporučená dotace', 1, @a + 42),
(2, 'recommended-deposit', '', '', 1, @a + 42),
(16, 'recommended-deposit', '', '', 1, @a + 42),
(1, 'recommended-withdraw', '', 'Doporučený odvod', 1, @a + 43),
(2, 'recommended-withdraw', '', '', 1, @a + 43),
(16, 'recommended-withdraw', '', '', 1, @a + 43),
(1, 'withdraw', '', 'Odvod', 1, @a + 44),
(2, 'withdraw', '', '', 1, @a + 44),
(16, 'withdraw', '', '', 1, @a + 44),
(1, 'actions', '', 'Akce', 1, @a + 45),
(2, 'actions', '', '', 1, @a + 45),
(16, 'actions', '', '', 1, @a + 45),
(1, 'fund', '', 'dotovat/odvést', 1, @a + 46),
(2, 'fund', '', '', 1, @a + 46),
(16, 'fund', '', '', 1, @a + 46),
(1, 'reset', '', 'obnovit', 1, @a + 48),
(2, 'reset', '', '', 1, @a + 48),
(16, 'reset', '', '', 1, @a + 48),
(1, 'null', '', 'nulový', 0, @a + 49),
(2, 'null', '', '', 1, @a + 49),
(16, 'null', '', '', 0, @a + 49),
(1, 'name', '', 'Název', 1, @a + 50),
(2, 'name', '', '', 1, @a + 50),
(16, 'name', '', '', 1, @a + 50),
(1, 'Please select type of transaction first.', '', 'Vyberte nejdříve typ transakce.', 1, @a + 51),
(2, 'Please select type of transaction first.', '', '', 1, @a + 51),
(16, 'Please select type of transaction first.', '', '', 1, @a + 51),
(1, 'Cancel-transaction', '', 'Stornovat transakci', 1, @a + 52),
(2, 'Cancel-transaction', '', '', 1, @a + 52),
(16, 'Cancel-transaction', '', '', 1, @a + 52),
(1, 'Transactions to export', '', 'Transkace k exportu', 0, @a + 53),
(2, 'Transactions to export', '', '', 0, @a + 53),
(16, 'Transactions to export', '', '', 0, @a + 53),
(1, 'No transactions to export', '', 'Žádné transakce nebyly nalezeny', 0, @a + 54),
(2, 'No transactions to export', '', '', 0, @a + 54),
(16, 'No transactions to export', '', '', 0, @a + 54),
(1, 'Older exports', '', 'Starší exporty', 0, @a + 55),
(2, 'Older exports', '', '', 0, @a + 55),
(16, 'Older exports', '', '', 0, @a + 55),
(1, 'No export found', '', 'Žádné exporty nebyly nalezeny', 0, @a + 56),
(2, 'No export found', '', '', 0, @a + 56),
(16, 'No export found', '', '', 0, @a + 56),
(1, 'Confirmations export', '', 'Export příkazů k úhradě', 0, @a + 57),
(2, 'Confirmations export', '', '', 0, @a + 57),
(16, 'Confirmations export', '', '', 0, @a + 57),
(1, 'Currency', '', 'Měna', 1, @a + 58),
(2, 'Currency', '', '', 1, @a + 58),
(16, 'Currency', '', '', 1, @a + 58),
(1, 'Notes', '', 'Poznámky', 1, @a + 59),
(2, 'Notes', '', '', 1, @a + 59),
(16, 'Notes', '', '', 1, @a + 59),
(1, 'User nick', '', 'Přezdívka uživ.', 1, @a + 60),
(2, 'User nick', '', '', 1, @a + 60),
(16, 'User nick', '', '', 1, @a + 60),
(1, 'Manual transaction', '', 'Manuální transakce', 1, @a + 61),
(2, 'Manual transaction', '', '', 1, @a + 61),
(16, 'Manual transaction', '', '', 1, @a + 61),
(1, 'manual-deposit', '', 'Vložit na účet', 1, @a + 62),
(2, 'manual-deposit', '', '', 1, @a + 62),
(16, 'manual-deposit', '', '', 1, @a + 62),
(1, 'manual-withdraw', '', 'Odebrat z účtu', 1, @a + 63),
(2, 'manual-withdraw', '', '', 1, @a + 63),
(16, 'manual-withdraw', '', '', 1, @a + 63),
(1, 'manual-balance', '', 'Upravit stav účtu', 1, @a + 64),
(2, 'manual-balance', '', '', 1, @a + 64),
(16, 'manual-balance', '', '', 1, @a + 64),
(1, 'manual-points', '', 'Upravit stav bodového konta', 0, @a + 66),
(2, 'manual-points', '', '', 1, @a + 66),
(16, 'manual-points', '', '', 0, @a + 66),
(1, 'Online Card', '', 'Platební karta', 1, @a + 67),
(2, 'Online Card', '', '', 1, @a + 67),
(16, 'Online Card', '', '', 1, @a + 67),
(1, 'Bank transfer', '', 'Bankovním převodem', 1, @a + 68),
(2, 'Bank transfer', '', '', 1, @a + 68),
(16, 'Bank transfer', '', '', 1, @a + 68),
(1, 'deposit type', '', 'Typ vkladu', 0, @a + 70),
(2, 'deposit type', '', '', 1, @a + 70),
(16, 'deposit type', '', '', 0, @a + 70),
(1, 'insert-transaction', '', 'Odeslat transakci', 1, @a + 71),
(2, 'insert-transaction', '', '', 1, @a + 71),
(16, 'insert-transaction', '', '', 1, @a + 71),
(1, 'Are you sure to commit the transaction?', '', 'Jste si jisti, že chcete odeslat tuto transakci?', 1, @a + 72),
(2, 'Are you sure to commit the transaction?', '', '', 1, @a + 72),
(16, 'Are you sure to commit the transaction?', '', '', 1, @a + 72),
(1, 'confirm-transaction', '', 'Potvrdit odeslání', 1, @a + 73),
(2, 'confirm-transaction', '', '', 1, @a + 73),
(16, 'confirm-transaction', '', '', 1, @a + 73),
(1, 'insert-transaction-successful', '', 'Transakce byla úspěšně vložena', 1, @a + 74),
(2, 'insert-transaction-successful', '', '', 1, @a + 74),
(16, 'insert-transaction-successful', '', '', 1, @a + 74),
(1, 'amount-to-balance', '', 'Částka na kterou nastavit účet uživatele', 1, @a + 75),
(2, 'amount-to-balance', '', '', 1, @a + 75),
(16, 'amount-to-balance', '', '', 1, @a + 75),
(1, 'edit', '', 'Upravit', 1, @a + 76),
(2, 'edit', '', '', 1, @a + 76),
(16, 'edit', '', '', 1, @a + 76),
(1, 'editable', '', 'měnitelný', 0, @a + 79),
(2, 'editable', '', '', 1, @a + 79),
(16, 'editable', '', '', 0, @a + 79),
(1, 'not_editable', '', 'neměnitelný', 0, @a + 80),
(2, 'not_editable', '', '', 1, @a + 80),
(16, 'not_editable', '', '', 0, @a + 80),
(1, 'system_params', '', 'Systémové', 1, @a + 81),
(2, 'system_params', '', '', 1, @a + 81),
(16, 'system_params', '', '', 1, @a + 81),
(1, 'branch_params', '', 'Pobočkové', 1, @a + 82),
(2, 'branch_params', '', '', 1, @a + 82),
(16, 'branch_params', '', '', 1, @a + 82),
(1, 'user_params', '', 'Uživatelské', 1, @a + 83),
(2, 'user_params', '', '', 1, @a + 83),
(16, 'user_params', '', '', 1, @a + 83),
(1, 'system_parameter_defaults', '', 'Vychozí hodnoty sys. parametrů', 1, @a + 84),
(2, 'system_parameter_defaults', '', '', 1, @a + 84),
(16, 'system_parameter_defaults', '', '', 1, @a + 84),
(1, 'branch_parameter_defaults', '', 'Výchozí hodnoty pobočkových parametrů (v případě, že pobočka parametr nepřetěžuje, je použit tento)', 1, @a + 85),
(2, 'branch_parameter_defaults', '', '', 1, @a + 85),
(16, 'branch_parameter_defaults', '', '', 1, @a + 85),
(1, 'user_parameter_defaults', '', 'Výchozí hodnoty uživatelských parametrů (v případě, že uživatel parametr nepřetěžuje, je použit tento)', 1, @a + 86),
(2, 'user_parameter_defaults', '', '', 1, @a + 86),
(16, 'user_parameter_defaults', '', '', 1, @a + 86),
(1, 'cancel', '', 'Zrušit', 0, @a + 87),
(2, 'cancel', '', '', 0, @a + 87),
(16, 'cancel', '', '', 0, @a + 87),
(1, 'transaction_fees', '', 'Poplatky za transakci', 0, @a + 88),
(2, 'transaction_fees', '', '', 0, @a + 88),
(16, 'transaction_fees', '', '', 0, @a + 88),
(1, 'transaction_limits', '', 'Transakční limity', 0, @a + 89),
(2, 'transaction_limits', '', '', 0, @a + 89),
(16, 'transaction_limits', '', '', 0, @a + 89),
(1, 'Low Limit', '', 'Dolní limit', 0, @a + 90),
(2, 'Low Limit', '', '', 0, @a + 90),
(16, 'Low Limit', '', '', 0, @a + 90),
(1, 'High Limit', '', 'Horní limit', 0, @a + 91),
(2, 'High Limit', '', '', 0, @a + 91),
(16, 'High Limit', '', '', 0, @a + 91),
(1, 'fixed_fee_value', '', 'Fixní poplatek', 0, @a + 92),
(2, 'fixed_fee_value', '', '', 0, @a + 92),
(16, 'fixed_fee_value', '', '', 0, @a + 92),
(1, 'relative_fee_value', '', 'Procentuální poplatek', 0, @a + 93),
(2, 'relative_fee_value', '', '', 0, @a + 93),
(16, 'relative_fee_value', '', '', 0, @a + 93),
(1, 'Bet limits per sport/day', '', 'Limit na sázku na sport za den', 0, @a + 94),
(2, 'Bet limits per sport/day', '', '', 0, @a + 94),
(16, 'Bet limits per sport/day', '', '', 0, @a + 94),
(1, 'Users', '', 'Uživatelé', 0, @a + 95),
(2, 'Users', '', '', 0, @a + 95),
(16, 'Users', '', '', 0, @a + 95),
(1, 'First name', '', 'Jméno', 0, @a + 96),
(2, 'First name', '', '', 0, @a + 96),
(16, 'First name', '', '', 0, @a + 96),
(1, 'Last name', '', 'Příjmení', 0, @a + 97),
(2, 'Last name', '', '', 0, @a + 97),
(16, 'Last name', '', '', 0, @a + 97),
(1, 'Username', '', 'Přezdívka', 0, @a + 98),
(2, 'Username', '', '', 0, @a + 98),
(16, 'Username', '', '', 0, @a + 98),
(1, 'Birth Date', '', 'Datum nar.', 0, @a + 99),
(2, 'Birth Date', '', '', 0, @a + 99),
(16, 'Birth Date', '', '', 0, @a + 99),
(1, 'Registration Date', '', 'Datum reg.', 0, @a + 100),
(2, 'Registration Date', '', '', 0, @a + 100),
(16, 'Registration Date', '', '', 0, @a + 100),
(1, 'user_home_branch', '', 'Dom. pobočka', 0, @a + 101),
(2, 'user_home_branch', '', '', 0, @a + 101),
(16, 'user_home_branch', '', '', 0, @a + 101),
(1, 'insert_user', '', 'Založit uživatele', 0, @a + 102),
(2, 'insert_user', '', '', 0, @a + 102),
(16, 'insert_user', '', '', 0, @a + 102),
(1, 'ban_selected', '', 'Zakázat vybrané', 0, @a + 103),
(2, 'ban_selected', '', '', 0, @a + 103),
(16, 'ban_selected', '', '', 0, @a + 103),
(1, 'allow_selected', '', 'Povolit vybrané', 0, @a + 104),
(2, 'allow_selected', '', '', 0, @a + 104),
(16, 'allow_selected', '', '', 0, @a + 104),
(1, 'allow_user', '', 'Povolit', 0, @a + 105),
(2, 'allow_user', '', '', 0, @a + 105),
(16, 'allow_user', '', '', 0, @a + 105),
(1, 'ban_user', '', 'Zakázat', 0, @a + 106),
(2, 'ban_user', '', '', 0, @a + 106),
(16, 'ban_user', '', '', 0, @a + 106),
(1, 'question_ban_user', '', 'Chcete opravdu zakázat tohoto uživatele?', 0, @a + 107),
(2, 'question_ban_user', '', '', 0, @a + 107),
(16, 'question_ban_user', '', '', 0, @a + 107),
(1, 'question_allow_user', '', 'Chcete opravdu povolit tohoto uživatele?', 0, @a + 108),
(2, 'question_allow_user', '', '', 0, @a + 108),
(16, 'question_allow_user', '', '', 0, @a + 108),
(1, 'user_detail', '', 'Náhled', 0, @a + 109),
(2, 'user_detail', '', '', 0, @a + 109),
(16, 'user_detail', '', '', 0, @a + 109),
(1, 'user_profile', '', 'Profil', 0, @a + 110),
(2, 'user_profile', '', '', 0, @a + 110),
(16, 'user_profile', '', '', 0, @a + 110),
(1, 'user_balance', '', 'Finance a body', 0, @a + 111),
(2, 'user_balance', '', '', 0, @a + 111),
(16, 'user_balance', '', '', 0, @a + 111),
(1, 'password', '', 'Heslo', 1, @a + 112),
(2, 'password', '', '', 1, @a + 112),
(16, 'password', '', '', 1, @a + 112),
(1, 'user_notes', '', 'Poznámky', 1, @a + 113),
(2, 'user_notes', '', '', 1, @a + 113),
(16, 'user_notes', '', '', 1, @a + 113),
(1, 'user_bookmaker_notes', '', 'Poznámky bookmakerů', 1, @a + 114),
(2, 'user_bookmaker_notes', '', '', 1, @a + 114),
(16, 'user_bookmaker_notes', '', '', 1, @a + 114),
(1, 'user_match_check', '', 'Kontrola shody', 1, @a + 115),
(2, 'user_match_check', '', '', 1, @a + 115),
(16, 'user_match_check', '', '', 1, @a + 115),
(1, 'user_bet_stats', '', 'Statistiky sázek', 1, @a + 116),
(2, 'user_bet_stats', '', '', 1, @a + 116),
(16, 'user_bet_stats', '', '', 1, @a + 116),
(1, 'user_profile_params', '', 'Uživatelské parametry', 1, @a + 117),
(2, 'user_profile_params', '', '', 1, @a + 117),
(16, 'user_profile_params', '', '', 1, @a + 117),
(1, 'delete', '', 'Smazat', 1, @a + 118),
(2, 'delete', '', '', 1, @a + 118),
(16, 'delete', '', '', 1, @a + 118),
(1, 'hide', '', 'Schovat', 1, @a + 119),
(2, 'hide', '', '', 1, @a + 119),
(16, 'hide', '', '', 1, @a + 119),
(1, 'detail', '', 'Náhled', 1, @a + 120),
(2, 'detail', '', '', 1, @a + 120),
(16, 'detail', '', '', 1, @a + 120),
(1, 'insert_event', '', 'Založit událost', 1, @a + 121),
(2, 'insert_event', '', '', 1, @a + 121),
(16, 'insert_event', '', '', 1, @a + 121),
(1, 'event_delete_ok', '', 'Událost byla úspěšně smazána.', 1, @a + 122),
(2, 'event_delete_ok', '', '', 1, @a + 122),
(16, 'event_delete_ok', '', '', 1, @a + 122),
(1, 'event_delete_error', '', 'Chyba při mazání událost.', 1, @a + 123),
(2, 'event_delete_error', '', '', 1, @a + 123),
(16, 'event_delete_error', '', '', 1, @a + 123),
(1, 'event_show_ok', '', 'Událost byla zobrazena.', 1, @a + 124),
(2, 'event_show_ok', '', '', 1, @a + 124),
(16, 'event_show_ok', '', '', 1, @a + 124),
(1, 'event_show_error', '', 'Chyba při nastavení zobrazování události.', 1, @a + 125),
(2, 'event_show_error', '', '', 1, @a + 125),
(16, 'event_show_error', '', '', 1, @a + 125),
(1, 'event_hide_ok', '', 'Událost byl schována.', 1, @a + 126),
(2, 'event_hide_ok', '', '', 1, @a + 126),
(16, 'event_hide_ok', '', '', 1, @a + 126),
(1, 'event_hide_error', '', 'Vyskytla se chyba při schování události.', 1, @a + 127),
(2, 'event_hide_error', '', '', 1, @a + 127),
(16, 'event_hide_error', '', '', 1, @a + 127),
(1, 'betradar_id', '', 'ID betradaru', 1, @a + 128),
(2, 'betradar_id', '', '', 1, @a + 128),
(16, 'betradar_id', '', '', 1, @a + 128),
(1, 'bet_alias_from', '', 'Alias od', 1, @a + 129),
(2, 'bet_alias_from', '', '', 1, @a + 129),
(16, 'bet_alias_from', '', '', 1, @a + 129),
(1, 'bet_alias_to', '', 'Alias do', 1, @a + 130),
(2, 'bet_alias_to', '', '', 1, @a + 130),
(16, 'bet_alias_to', '', '', 1, @a + 130),
(1, 'valid_from', '', 'Platná od', 1, @a + 131),
(2, 'valid_from', '', '', 1, @a + 131),
(16, 'valid_from', '', '', 1, @a + 131),
(1, 'valid_to', '', 'Platná do', 1, @a + 132),
(2, 'valid_to', '', '', 1, @a + 132),
(16, 'valid_to', '', '', 1, @a + 132),
(1, 'event_marked', '', 'Označení', 1, @a + 133),
(2, 'event_marked', '', '', 1, @a + 133),
(16, 'event_marked', '', '', 1, @a + 133),
(1, 'event_separate', '', 'Separátní', 1, @a + 134),
(2, 'event_separate', '', '', 1, @a + 134),
(16, 'event_separate', '', '', 1, @a + 134),
(1, 'betradar_event_id', '', 'Betradar ID události', 0, @a + 136),
(2, 'betradar_event_id', '', '', 1, @a + 136),
(16, 'betradar_event_id', '', '', 0, @a + 136),
(1, 'bet_id', '', 'ID sázky', 1, @a + 137),
(2, 'bet_id', '', '', 1, @a + 137),
(16, 'bet_id', '', '', 1, @a + 137),
(1, 'bet_alias', '', 'Alias sázky', 1, @a + 138),
(2, 'bet_alias', '', '', 1, @a + 138),
(16, 'bet_alias', '', '', 1, @a + 138),
(1, 'group_combinations', '', 'Seskupit kombinace', 1, @a + 139),
(2, 'group_combinations', '', '', 1, @a + 139),
(16, 'group_combinations', '', '', 1, @a + 139),
(1, 'all_events', '', 'všechny události', 1, @a + 140),
(2, 'all_events', '', '', 1, @a + 140),
(16, 'all_events', '', '', 1, @a + 140),
(1, 'all_sports', '', 'Všechny sporty', 1, @a + 141),
(2, 'all_sports', '', '', 1, @a + 141),
(16, 'all_sports', '', '', 1, @a + 141),
(1, 'ticket_status', '', 'Stav tiketu', 1, @a + 142),
(2, 'ticket_status', '', '', 1, @a + 142),
(16, 'ticket_status', '', '', 1, @a + 142),
(1, 'events', '', 'Události', 1, @a + 143),
(2, 'events', '', '', 1, @a + 143),
(16, 'events', '', '', 1, @a + 143),
(1, 'bet_status_current', '', 'Aktuální', 1, @a + 144),
(2, 'bet_status_current', '', '', 1, @a + 144),
(16, 'bet_status_current', '', '', 1, @a + 144),
(1, 'bet_status_unevaluated', '', 'Nevyhodnocená', 1, @a + 145),
(2, 'bet_status_unevaluated', '', '', 1, @a + 145),
(16, 'bet_status_unevaluated', '', '', 1, @a + 145),
(1, 'bet_status_evaluated', '', 'Vyhodnocená', 1, @a + 146),
(2, 'bet_status_evaluated', '', '', 1, @a + 146),
(16, 'bet_status_evaluated', '', '', 1, @a + 146),
(1, 'bet_status_confirmed', '', 'Potvrzená', 1, @a + 147),
(2, 'bet_status_confirmed', '', '', 1, @a + 147),
(16, 'bet_status_confirmed', '', '', 1, @a + 147),
(1, 'bet_status_canceled', '', 'Zrušená', 1, @a + 148),
(2, 'bet_status_canceled', '', '', 1, @a + 148),
(16, 'bet_status_canceled', '', '', 1, @a + 148),
(1, 'bet_status_paid_out', '', 'Vyplacená', 1, @a + 149),
(2, 'bet_status_paid_out', '', '', 1, @a + 149),
(16, 'bet_status_paid_out', '', '', 1, @a + 149),
(1, 'bet_status_suspended', '', 'Pozastavená', 1, @a + 150),
(2, 'bet_status_suspended', '', '', 1, @a + 150),
(16, 'bet_status_suspended', '', '', 1, @a + 150),
(1, 'apply_bet_filter', '', 'Vybrat', 1, @a + 151),
(2, 'apply_bet_filter', '', '', 1, @a + 151),
(16, 'apply_bet_filter', '', '', 1, @a + 151),
(1, 'bet_set_date', '', 'Datum', 1, @a + 152),
(2, 'bet_set_date', '', '', 1, @a + 152),
(16, 'bet_set_date', '', '', 1, @a + 152),
(1, 'bet_select_all', '', 'Vybrat vše', 1, @a + 153),
(2, 'bet_select_all', '', '', 1, @a + 153),
(16, 'bet_select_all', '', '', 1, @a + 153),
(1, 'bet_activate_selected', '', 'Aktivovat označené', 1, @a + 154),
(2, 'bet_activate_selected', '', '', 1, @a + 154),
(16, 'bet_activate_selected', '', '', 1, @a + 154),
(1, 'question_activate_selected_bets', '', 'Opravdu aktivovat označené sázky?', 1, @a + 155),
(2, 'question_activate_selected_bets', '', '', 1, @a + 155),
(16, 'question_activate_selected_bets', '', '', 1, @a + 155),
(1, 'bet_suspend_selected', '', 'Pozastavit označené', 1, @a + 156),
(2, 'bet_suspend_selected', '', '', 1, @a + 156),
(16, 'bet_suspend_selected', '', '', 1, @a + 156),
(1, 'question_suspend_selected_bets', '', 'Opravdu chcete pozastavit označené sázky?', 1, @a + 157),
(2, 'question_suspend_selected_bets', '', '', 1, @a + 157),
(16, 'question_suspend_selected_bets', '', '', 1, @a + 157),
(1, 'bet_cancel_selected', '', 'Zrušit označené', 1, @a + 158),
(2, 'bet_cancel_selected', '', '', 1, @a + 158),
(16, 'bet_cancel_selected', '', '', 1, @a + 158),
(1, 'question_cancel_selected_bets', '', 'Opravdu chcete zrušit označené sázky?', 1, @a + 159),
(2, 'question_cancel_selected_bets', '', '', 1, @a + 159),
(16, 'question_cancel_selected_bets', '', '', 1, @a + 159),
(1, 'bet_renew_selected', '', 'Obnovit označené', 1, @a + 160),
(2, 'bet_renew_selected', '', '', 1, @a + 160),
(16, 'bet_renew_selected', '', '', 1, @a + 160),
(1, 'question_renew_selected_bets', '', 'Opravdu chcete obnovit označené sázky?', 1, @a + 161),
(2, 'question_renew_selected_bets', '', '', 1, @a + 161),
(16, 'question_renew_selected_bets', '', '', 1, @a + 161),
(1, 'bet_confirm_selected', '', 'Potvrdit označené', 1, @a + 162),
(2, 'bet_confirm_selected', '', '', 1, @a + 162),
(16, 'bet_confirm_selected', '', '', 1, @a + 162),
(1, 'question_confirm_selected_bets', '', 'Opravdu chcete potvrdit označené sázky?', 1, @a + 163),
(2, 'question_confirm_selected_bets', '', '', 1, @a + 163),
(16, 'question_confirm_selected_bets', '', '', 1, @a + 163),
(1, 'bet_cancel_confirmation_selected', '', 'Zrušit potvrzení označených', 1, @a + 164),
(2, 'bet_cancel_confirmation_selected', '', '', 1, @a + 164),
(16, 'bet_cancel_confirmation_selected', '', '', 1, @a + 164),
(1, 'question_cancel_confirmation_selected_bets', '', 'Opravdu chcete zrušit potvrzení označených sázek?', 1, @a + 165),
(2, 'question_cancel_confirmation_selected_bets', '', '', 1, @a + 165),
(16, 'question_cancel_confirmation_selected_bets', '', '', 1, @a + 165),
(1, 'expand_collapse_all', '', 'Rozbalit/zabalit vše', 1, @a + 166),
(2, 'expand_collapse_all', '', '', 1, @a + 166),
(16, 'expand_collapse_all', '', '', 1, @a + 166),
(1, 'bet_update_all', '', 'Aktualizovat vše', 1, @a + 167),
(2, 'bet_update_all', '', '', 1, @a + 167),
(16, 'bet_update_all', '', '', 1, @a + 167),
(1, 'warn_no_bets_found', '', 'Žádné sázky nebyly nalezeny. Změňte/zvolte kritéria filtru.', 0, @a + 169),
(2, 'warn_no_bets_found', '', '', 1, @a + 169),
(16, 'warn_no_bets_found', '', '', 0, @a + 169),
(1, 'bet_text', '', 'Text sázky', 1, @a + 170),
(2, 'bet_text', '', '', 1, @a + 170),
(16, 'bet_text', '', '', 1, @a + 170),
(1, 'bet_ticket_text', '', 'Text sázky na tiketu', 1, @a + 171),
(2, 'bet_ticket_text', '', '', 1, @a + 171),
(16, 'bet_ticket_text', '', '', 1, @a + 171),
(1, 'disable_betradar_update', '', 'Zakázat update z betradaru', 1, @a + 172),
(2, 'disable_betradar_update', '', '', 1, @a + 172),
(16, 'disable_betradar_update', '', '', 1, @a + 172),
(1, 'enable_betradar_update', '', 'Povolit update z betradaru', 1, @a + 173),
(2, 'enable_betradar_update', '', '', 1, @a + 173),
(16, 'enable_betradar_update', '', '', 1, @a + 173),
(1, 'bet_change_status_cancel', '', 'Zrušit', 0, @a + 176),
(2, 'bet_change_status_cancel', '', '', 1, @a + 176),
(16, 'bet_change_status_cancel', '', '', 0, @a + 176),
(1, 'bet_change_status_renew', '', 'Obnovit', 0, @a + 177),
(2, 'bet_change_status_renew', '', '', 1, @a + 177),
(16, 'bet_change_status_renew', '', '', 0, @a + 177),
(1, 'bet_change_status_suspend', '', 'Pozastavit', 1, @a + 178),
(2, 'bet_change_status_suspend', '', '', 1, @a + 178),
(16, 'bet_change_status_suspend', '', '', 1, @a + 178),
(1, 'bet_change_status_activate', '', 'Aktivovat', 1, @a + 179),
(2, 'bet_change_status_activate', '', '', 1, @a + 179),
(16, 'bet_change_status_activate', '', '', 1, @a + 179),
(1, 'bet_change_status_confirm', '', 'Potvrdit', 1, @a + 180),
(2, 'bet_change_status_confirm', '', '', 1, @a + 180),
(16, 'bet_change_status_confirm', '', '', 1, @a + 180),
(1, 'bet_change_status_cancel_confirmation', '', 'Zrušit potvrzení', 1, @a + 181),
(2, 'bet_change_status_cancel_confirmation', '', '', 1, @a + 181),
(16, 'bet_change_status_cancel_confirmation', '', '', 1, @a + 181),
(1, 'bet_change_status_revert_to_unevaluated', '', 'Změnit na nevyhodnocenou', 1, @a + 182),
(2, 'bet_change_status_revert_to_unevaluated', '', '', 1, @a + 182),
(16, 'bet_change_status_revert_to_unevaluated', '', '', 1, @a + 182),
(1, 'edit_bet', '', 'Uložit změny', 1, @a + 183),
(2, 'edit_bet', '', '', 1, @a + 183),
(16, 'edit_bet', '', '', 1, @a + 183),
(1, 'edit_bet_and_rates', '', 'Uložit sázky a kurzy', 1, @a + 184),
(2, 'edit_bet_and_rates', '', '', 1, @a + 184),
(16, 'edit_bet_and_rates', '', '', 1, @a + 184),
(1, 'lister_total_pages', '', 'stran', 1, @a + 185),
(2, 'lister_total_pages', '', '', 1, @a + 185),
(16, 'lister_total_pages', '', '', 1, @a + 185),
(1, 'lister_total_items', '', 'záznamů', 1, @a + 186),
(2, 'lister_total_items', '', '', 1, @a + 186),
(16, 'lister_total_items', '', '', 1, @a + 186),
(1, 'Previous', '', 'Předchozí', 1, @a + 187),
(2, 'Previous', '', '', 1, @a + 187),
(16, 'Previous', '', '', 1, @a + 187),
(1, 'ticket_status_collected', '', 'Výhra vybrána', 1, @a + 188),
(2, 'ticket_status_collected', '', '', 1, @a + 188),
(16, 'ticket_status_collected', '', '', 1, @a + 188),
(1, 'ticket_status_paid_out', '', 'Vyplacen', 1, @a + 189),
(2, 'ticket_status_paid_out', '', '', 1, @a + 189),
(16, 'ticket_status_paid_out', '', '', 1, @a + 189),
(1, 'ticket_status_not_paid_out', '', 'Nevyplacen', 1, @a + 190),
(2, 'ticket_status_not_paid_out', '', '', 1, @a + 190),
(16, 'ticket_status_not_paid_out', '', '', 1, @a + 190),
(1, 'ticket_status_winnings', '', 'Výhra', 1, @a + 191),
(2, 'ticket_status_winnings', '', '', 1, @a + 191),
(16, 'ticket_status_winnings', '', '', 1, @a + 191),
(1, 'date_from', '', 'Od', 0, @a + 192),
(2, 'date_from', '', '', 0, @a + 192),
(16, 'date_from', '', '', 0, @a + 192),
(1, 'date_to', '', 'Do', 0, @a + 193),
(2, 'date_to', '', '', 0, @a + 193),
(16, 'date_to', '', '', 0, @a + 193),
(1, 'ticket_id', '', 'Id tiketu', 0, @a + 194),
(2, 'ticket_id', '', '', 0, @a + 194),
(16, 'ticket_id', '', '', 0, @a + 194),
(1, 'warn_no_tickets_found', '', 'Žádné tikety nebyly nalezeny. Změnte/zvolte kritéria filtru.', 0, @a + 195),
(2, 'warn_no_tickets_found', '', '', 0, @a + 195),
(16, 'warn_no_tickets_found', '', '', 0, @a + 195),
(1, 'branch_id', '', 'ID pobočky', 0, @a + 196),
(2, 'branch_id', '', '', 0, @a + 196),
(16, 'branch_id', '', '', 0, @a + 196),
(1, 'event_id', '', 'ID události', 0, @a + 197),
(2, 'event_id', '', '', 0, @a + 197),
(16, 'event_id', '', '', 0, @a + 197),
(1, 'user', '', 'Uživatel', 0, @a + 198),
(2, 'user', '', '', 0, @a + 198),
(16, 'user', '', '', 0, @a + 198),
(1, 'ticket_branch', '', 'Pobočka', 0, @a + 199),
(2, 'ticket_branch', '', '', 0, @a + 199),
(16, 'ticket_branch', '', '', 0, @a + 199),
(1, 'ticket_bet_count', '', 'Poč. sázek', 0, @a + 200),
(2, 'ticket_bet_count', '', '', 0, @a + 200),
(16, 'ticket_bet_count', '', '', 0, @a + 200),
(1, 'ticket_group_count', '', 'Poč. skupin', 0, @a + 201),
(2, 'ticket_group_count', '', '', 0, @a + 201),
(16, 'ticket_group_count', '', '', 0, @a + 201),
(1, 'ticket_winning', '', 'EVA', 0, @a + 203),
(2, 'ticket_winning', '', '', 0, @a + 203),
(16, 'ticket_winning', '', '', 0, @a + 203),
(1, 'ticket_date_created', '', 'Datum založení', 0, @a + 204),
(2, 'ticket_date_created', '', '', 0, @a + 204),
(16, 'ticket_date_created', '', '', 0, @a + 204),
(1, 'ticket_evaluation', '', 'Vyhodnocení', 0, @a + 205),
(2, 'ticket_evaluation', '', '', 0, @a + 205),
(16, 'ticket_evaluation', '', '', 0, @a + 205),
(1, 'ticket_pay_out_date', '', 'Datum výplaty', 0, @a + 207),
(2, 'ticket_pay_out_date', '', '', 0, @a + 207),
(16, 'ticket_pay_out_date', '', '', 0, @a + 207),
(1, 'ticket_type', '', 'typ', 0, @a + 208),
(2, 'ticket_type', '', '', 0, @a + 208),
(16, 'ticket_type', '', '', 0, @a + 208),
(1, 'note', '', 'Poznámka', 0, @a + 209),
(2, 'note', '', '', 0, @a + 209),
(16, 'note', '', '', 0, @a + 209),
(1, 'action', '', 'Akce', 0, @a + 210),
(2, 'action', '', '', 0, @a + 210),
(16, 'action', '', '', 0, @a + 210),
(1, 'ticket_bookmaker_paid_off', '', 'Vyplatil BM ID', 0, @a + 211),
(2, 'ticket_bookmaker_paid_off', '', '', 0, @a + 211),
(16, 'ticket_bookmaker_paid_off', '', '', 0, @a + 211),
(1, 'cancel_ticket', '', 'Stornovat tiket', 0, @a + 212),
(2, 'cancel_ticket', '', '', 0, @a + 212),
(16, 'cancel_ticket', '', '', 0, @a + 212),
(1, 'ticket_rate_1', '', 'Vyplatit v kurzu 1', 0, @a + 213),
(2, 'ticket_rate_1', '', '', 0, @a + 213),
(16, 'ticket_rate_1', '', '', 0, @a + 213),
(1, 'question_want_rate_ticket_1', '', 'Opravdu chcete vyplatit tiket v kurzu 1?', 0, @a + 214),
(2, 'question_want_rate_ticket_1', '', '', 0, @a + 214),
(16, 'question_want_rate_ticket_1', '', '', 0, @a + 214),
(1, 'question_want_cancel_ticket', '', 'Opravdu chcete stornovat tiket?', 0, @a + 215),
(2, 'question_want_cancel_ticket', '', '', 0, @a + 215),
(16, 'question_want_cancel_ticket', '', '', 0, @a + 215),
(1, 'ticket_canceled_by_book_id', '', 'Tiket byl stornován bookmakerem ID', 0, @a + 216),
(2, 'ticket_canceled_by_book_id', '', '', 0, @a + 216),
(16, 'ticket_canceled_by_book_id', '', '', 0, @a + 216),
(1, 'ticket_cancel_reason', '', 'Důvod storna tiketu:', 0, @a + 217),
(2, 'ticket_cancel_reason', '', '', 0, @a + 217),
(16, 'ticket_cancel_reason', '', '', 0, @a + 217),
(1, 'ticket_cancellation_allowed', '', 'Storno tiketu povoleno', 0, @a + 218),
(2, 'ticket_cancellation_allowed', '', '', 0, @a + 218),
(16, 'ticket_cancellation_allowed', '', '', 0, @a + 218),
(1, 'ticket_status_loss', '', 'Prohra', 0, @a + 220),
(2, 'ticket_status_loss', '', '', 0, @a + 220),
(16, 'ticket_status_loss', '', '', 0, @a + 220),
(1, 'ticket_status_winning', '', 'Výhra', 0, @a + 221),
(2, 'ticket_status_winning', '', '', 0, @a + 221),
(16, 'ticket_status_winning', '', '', 0, @a + 221),
(1, 'ticket_status_canceled', '', 'Stornován', 0, @a + 222),
(2, 'ticket_status_canceled', '', '', 0, @a + 222),
(16, 'ticket_status_canceled', '', '', 0, @a + 222),
(1, 'question_want_renew_ticket', '', 'Chcete opravdu obnovit tento tiket?', 1, @a + 223),
(2, 'question_want_renew_ticket', '', '', 1, @a + 223),
(16, 'question_want_renew_ticket', '', '', 1, @a + 223),
(1, 'renew_ticket', '', 'Obnovit tiket', 1, @a + 224),
(2, 'renew_ticket', '', '', 1, @a + 224),
(16, 'renew_ticket', '', '', 1, @a + 224),
(1, 'branch_main', '', 'Profil', 1, @a + 225),
(2, 'branch_main', '', '', 1, @a + 225),
(16, 'branch_main', '', '', 1, @a + 225),
(1, 'branch_parameters', '', 'Parametry', 1, @a + 226),
(2, 'branch_parameters', '', '', 1, @a + 226),
(16, 'branch_parameters', '', '', 1, @a + 226),
(1, 'branch_bank_accounts', '', 'Bankovní účty', 1, @a + 227),
(2, 'branch_bank_accounts', '', '', 1, @a + 227),
(16, 'branch_bank_accounts', '', '', 1, @a + 227),
(1, 'branch_contracts', '', 'Smlouvy', 1, @a + 228),
(2, 'branch_contracts', '', '', 1, @a + 228),
(16, 'branch_contracts', '', '', 1, @a + 228),
(1, 'branch_employees', '', 'Zaměstnanci pobočky', 1, @a + 229),
(2, 'branch_employees', '', '', 1, @a + 229),
(16, 'branch_employees', '', '', 1, @a + 229),
(1, 'branch_users', '', 'Hráči na pobočce', 1, @a + 230),
(2, 'branch_users', '', '', 1, @a + 230),
(16, 'branch_users', '', '', 1, @a + 230),
(1, 'branch_hosts', '', 'Počítače (stanice)', 1, @a + 231),
(2, 'branch_hosts', '', '', 1, @a + 231),
(16, 'branch_hosts', '', '', 1, @a + 231),
(1, 'branch_opening_hours', '', 'Otevírací doba', 1, @a + 232),
(2, 'branch_opening_hours', '', '', 1, @a + 232),
(16, 'branch_opening_hours', '', '', 1, @a + 232),
(1, 'view', '', 'Náhled', 1, @a + 233),
(2, 'view', '', '', 1, @a + 233),
(16, 'view', '', '', 1, @a + 233),
(1, 'insert_branch', '', 'Založit pobočku', 1, @a + 234),
(2, 'insert_branch', '', '', 1, @a + 234),
(16, 'insert_branch', '', '', 1, @a + 234),
(1, 'branch_contract', '', 'Smlouva pobočky', 1, @a + 235),
(2, 'branch_contract', '', '', 1, @a + 235),
(16, 'branch_contract', '', '', 1, @a + 235),
(1, 'branch_provider', '', 'Provozovatel pobočky', 1, @a + 236),
(2, 'branch_provider', '', '', 1, @a + 236),
(16, 'branch_provider', '', '', 1, @a + 236),
(1, 'manipulation_fees', '', 'Manipulační poplatky', 1, @a + 237),
(2, 'manipulation_fees', '', '', 1, @a + 237),
(16, 'manipulation_fees', '', '', 1, @a + 237),
(1, 'manipulation_fee', '', 'MP klasický', 1, @a + 238),
(2, 'manipulation_fee', '', '', 1, @a + 238),
(16, 'manipulation_fee', '', '', 1, @a + 238),
(1, 'manipulation_fee_win', '', 'MP výherní', 1, @a + 239),
(2, 'manipulation_fee_win', '', '', 1, @a + 239),
(16, 'manipulation_fee_win', '', '', 1, @a + 239),
(1, 'Address', '', 'Adresa', 1, @a + 240),
(2, 'Address', '', '', 1, @a + 240),
(16, 'Address', '', '', 1, @a + 240),
(1, 'Phone', '', 'Tel.', 1, @a + 241),
(2, 'Phone', '', '', 1, @a + 241),
(16, 'Phone', '', '', 1, @a + 241),
(1, 'branch_location', '', 'Kraj', 1, @a + 242),
(2, 'branch_location', '', '', 1, @a + 242),
(16, 'branch_location', '', '', 1, @a + 242),
(1, 'ticket_header', '', 'Hlavička tiketu', 1, @a + 243),
(2, 'ticket_header', '', '', 1, @a + 243),
(16, 'ticket_header', '', '', 1, @a + 243),
(1, 'branch_type', '', 'Typ provozovny', 1, @a + 244),
(2, 'branch_type', '', '', 1, @a + 244),
(16, 'branch_type', '', '', 1, @a + 244),
(1, 'provider_name', '', 'Jméno a příjmení provozovatele', 1, @a + 245),
(2, 'provider_name', '', '', 1, @a + 245),
(16, 'provider_name', '', '', 1, @a + 245),
(1, 'provider_ic', '', 'IČ provozovatele', 1, @a + 246),
(2, 'provider_ic', '', '', 1, @a + 246),
(16, 'provider_ic', '', '', 1, @a + 246),
(1, 'provider_dic', '', 'DIČ provozovatele', 1, @a + 247),
(2, 'provider_dic', '', '', 1, @a + 247),
(16, 'provider_dic', '', '', 1, @a + 247),
(1, 'provider_email', '', 'E-mail provozovatele', 1, @a + 248),
(2, 'provider_email', '', '', 1, @a + 248),
(16, 'provider_email', '', '', 1, @a + 248),
(1, 'provider_address', '', 'Adrese provozovatele', 1, @a + 249),
(2, 'provider_address', '', '', 1, @a + 249),
(16, 'provider_address', '', '', 1, @a + 249),
(1, 'Use Default [{0}]', '', 'Použít výchozí hodnotu [{0}]', 0, @a + 251),
(2, 'Use Default [{0}]', '', '', 0, @a + 251),
(16, 'Use Default [{0}]', '', '', 0, @a + 251),
(1, 'monday', '', 'Pondělí', 0, @a + 252),
(2, 'monday', '', '', 0, @a + 252),
(16, 'monday', '', '', 0, @a + 252),
(1, 'tuesday', '', 'Úterý', 0, @a + 253),
(2, 'tuesday', '', '', 0, @a + 253),
(16, 'tuesday', '', '', 0, @a + 253),
(1, 'wednesday', '', 'Středa', 0, @a + 254),
(2, 'wednesday', '', '', 0, @a + 254),
(16, 'wednesday', '', '', 0, @a + 254),
(1, 'thursday', '', 'Čtvrtek', 0, @a + 255),
(2, 'thursday', '', '', 0, @a + 255),
(16, 'thursday', '', '', 0, @a + 255),
(1, 'friday', '', 'Pátek', 0, @a + 256),
(2, 'friday', '', '', 0, @a + 256),
(16, 'friday', '', '', 0, @a + 256),
(1, 'saturday', '', 'Sobota', 0, @a + 257),
(2, 'saturday', '', '', 0, @a + 257),
(16, 'saturday', '', '', 0, @a + 257),
(1, 'sunday', '', 'Neděle', 0, @a + 258),
(2, 'sunday', '', '', 0, @a + 258),
(16, 'sunday', '', '', 0, @a + 258),
(1, 'closed', '', 'Zavřeno', 0, @a + 259),
(2, 'closed', '', '', 0, @a + 259),
(16, 'closed', '', '', 0, @a + 259),
(1, 'warn_no_bank_account_add_new', '', 'Není zadán bankovní účet. Pro přidání klikněte na "Upravit".', 0, @a + 260),
(2, 'warn_no_bank_account_add_new', '', '', 0, @a + 260),
(16, 'warn_no_bank_account_add_new', '', '', 0, @a + 260),
(1, 'bank_account_provision', '', 'Bankovní účet pro provize', 0, @a + 261),
(2, 'bank_account_provision', '', '', 0, @a + 261),
(16, 'bank_account_provision', '', '', 0, @a + 261),
(1, 'bank_account_balance', '', 'Bankovní účet pro dotace/odvody', 0, @a + 262),
(2, 'bank_account_balance', '', '', 0, @a + 262),
(16, 'bank_account_balance', '', '', 0, @a + 262),
(1, 'same_as_provision', '', 'Ǔčet je stejný jako pro provize', 0, @a + 263),
(2, 'same_as_provision', '', '', 0, @a + 263),
(16, 'same_as_provision', '', '', 0, @a + 263),
(1, 'update-ok', '', 'Záznam byl úspěšně zeditován.', 0, @a + 264),
(2, 'update-ok', '', '', 0, @a + 264),
(16, 'update-ok', '', '', 0, @a + 264),
(1, 'insert-ok', '', 'Záznam byl úspěšně vložen.', 0, @a + 265),
(2, 'insert-ok', '', '', 0, @a + 265),
(16, 'insert-ok', '', '', 0, @a + 265),
(1, 'notice_branch_created', '', 'Pobočka byla úspěšně založena', 0, @a + 266),
(2, 'notice_branch_created', '', '', 0, @a + 266),
(16, 'notice_branch_created', '', '', 0, @a + 266),
(1, 'notice_cont_creating_branch', '', 'Pokračujte ve vytváření pobočky..', 0, @a + 267),
(2, 'notice_cont_creating_branch', '', '', 0, @a + 267),
(16, 'notice_cont_creating_branch', '', '', 0, @a + 267),
(1, 'error_branch_user_creating', '', 'Nastala chyba při vytváření zástupného uživatele k pobočce', 0, @a + 268),
(2, 'error_branch_user_creating', '', '', 0, @a + 268),
(16, 'error_branch_user_creating', '', '', 0, @a + 268),
(1, 'error_form_not_valid_general', '', 'Chyba ve formuláři. Některá povinná pole nejsou nebo jsou chybně vyplněná.', 0, @a + 269),
(2, 'error_form_not_valid_general', '', '', 0, @a + 269),
(16, 'error_form_not_valid_general', '', '', 0, @a + 269),
(1, 'form_update_success_general', '', 'Záznam byl úspěšně zeditován.', 0, @a + 270),
(2, 'form_update_success_general', '', '', 0, @a + 270),
(16, 'form_update_success_general', '', '', 0, @a + 270),
(1, 'contract_cancel_ok', '', 'Smlouva byla úspěšně ukončena.', 0, @a + 271),
(2, 'contract_cancel_ok', '', '', 0, @a + 271),
(16, 'contract_cancel_ok', '', '', 0, @a + 271),
(1, 'contract_cancel_error', '', 'Vyskytla se chyba při ukončování smlouvy.', 0, @a + 272),
(2, 'contract_cancel_error', '', '', 0, @a + 272),
(16, 'contract_cancel_error', '', '', 0, @a + 272),
(1, 'warn_no_branch_employees', '', 'Pobočce nejsou přiřazení žádní zaměstnanci.', 0, @a + 273),
(2, 'warn_no_branch_employees', '', '', 0, @a + 273),
(16, 'warn_no_branch_employees', '', '', 0, @a + 273),
(1, 'nick_name', '', 'Přezdívka', 0, @a + 274),
(2, 'nick_name', '', '', 0, @a + 274),
(16, 'nick_name', '', '', 0, @a + 274),
(1, 'full_name', '', 'Jméno a příjmení', 0, @a + 275),
(2, 'full_name', '', '', 0, @a + 275),
(16, 'full_name', '', '', 0, @a + 275),
(1, 'show_employee_timesheet', '', 'Zobraz docházku zaměstnance', 0, @a + 276),
(2, 'show_employee_timesheet', '', '', 0, @a + 276),
(16, 'show_employee_timesheet', '', '', 0, @a + 276),
(1, 'Sex', '', 'Pohlaví', 0, @a + 277),
(2, 'Sex', '', '', 0, @a + 277),
(16, 'Sex', '', '', 0, @a + 277),
(1, 'warn_no_branch_users', '', 'Na pobočce nejsou žádní hráči.', 0, @a + 278),
(2, 'warn_no_branch_users', '', '', 0, @a + 278),
(16, 'warn_no_branch_users', '', '', 0, @a + 278),
(1, 'assign_users_to_branch', '', 'Přesunout vybrané hráče na jinou pobočku', 0, @a + 279),
(2, 'assign_users_to_branch', '', '', 0, @a + 279),
(16, 'assign_users_to_branch', '', '', 0, @a + 279),
(1, 'user_assign_ok', '', 'Přesun hráče(ů) úspěšně proveden.', 0, @a + 280),
(2, 'user_assign_ok', '', '', 0, @a + 280),
(16, 'user_assign_ok', '', '', 0, @a + 280),
(1, 'user_assign_error', '', 'Vyskytla se chyba při přesunu hráče(ů).', 0, @a + 281),
(2, 'user_assign_error', '', '', 0, @a + 281),
(16, 'user_assign_error', '', '', 0, @a + 281),
(1, 'host_name', '', 'Název stanice', 0, @a + 282),
(2, 'host_name', '', '', 0, @a + 282),
(16, 'host_name', '', '', 0, @a + 282),
(1, 'ip_address', '', 'IP adresa', 0, @a + 283),
(2, 'ip_address', '', '', 0, @a + 283),
(16, 'ip_address', '', '', 0, @a + 283),
(1, 'printer', '', 'Tiskárna', 0, @a + 284),
(2, 'printer', '', '', 0, @a + 284),
(16, 'printer', '', '', 0, @a + 284),
(1, 'display', '', 'Monitor', 0, @a + 285),
(2, 'display', '', '', 0, @a + 285),
(16, 'display', '', '', 0, @a + 285),
(1, 'windows_serial', '', 'Windows SN', 0, @a + 286),
(2, 'windows_serial', '', '', 0, @a + 286),
(16, 'windows_serial', '', '', 0, @a + 286),
(1, 'list_hosts', '', 'Seznam stanic', 0, @a + 287),
(2, 'list_hosts', '', '', 0, @a + 287),
(16, 'list_hosts', '', '', 0, @a + 287),
(1, 'insert_host', '', 'Vložit stanici', 0, @a + 288),
(2, 'insert_host', '', '', 0, @a + 288),
(16, 'insert_host', '', '', 0, @a + 288),
(1, 'Send message', '', 'Odeslání zprávy na pobočku', 0, @a + 289),
(2, 'Send message', '', '', 0, @a + 289),
(16, 'Send message', '', '', 0, @a + 289),
(1, 'message', '', 'Zpráva', 0, @a + 290),
(2, 'message', '', '', 0, @a + 290),
(16, 'message', '', '', 0, @a + 290),
(1, 'send', '', 'Odeslat', 0, @a + 291),
(2, 'send', '', '', 0, @a + 291),
(16, 'send', '', '', 0, @a + 291),
(1, 'ban_all', '', 'Zakázat všechny', 0, @a + 292),
(2, 'ban_all', '', '', 0, @a + 292),
(16, 'ban_all', '', '', 0, @a + 292),
(1, 'allow_all', '', 'Povolit všechny', 0, @a + 293),
(2, 'allow_all', '', '', 0, @a + 293),
(16, 'allow_all', '', '', 0, @a + 293),
(1, 'ban_all_in', '', 'Zakázat náběr všem', 0, @a + 294),
(2, 'ban_all_in', '', '', 0, @a + 294),
(16, 'ban_all_in', '', '', 0, @a + 294),
(1, 'allow_all_in', '', 'Povolit náběr všem', 0, @a + 295),
(2, 'allow_all_in', '', '', 0, @a + 295),
(16, 'allow_all_in', '', '', 0, @a + 295),
(1, 'ban_all_out', '', 'Zakázat vyplácení všem', 0, @a + 296),
(2, 'ban_all_out', '', '', 0, @a + 296),
(16, 'ban_all_out', '', '', 0, @a + 296),
(1, 'allow_all_out', '', 'Povolit vyplácení všem', 0, @a + 297),
(2, 'allow_all_out', '', '', 0, @a + 297),
(16, 'allow_all_out', '', '', 0, @a + 297),
(1, 'host_ban', '', 'Zakázat', 0, @a + 298),
(2, 'host_ban', '', '', 0, @a + 298),
(16, 'host_ban', '', '', 0, @a + 298),
(1, 'host_allow', '', 'Povolit', 0, @a + 299),
(2, 'host_allow', '', '', 0, @a + 299),
(16, 'host_allow', '', '', 0, @a + 299),
(1, 'host_ban_in', '', 'Zakázat náběr', 0, @a + 300),
(2, 'host_ban_in', '', '', 0, @a + 300),
(16, 'host_ban_in', '', '', 0, @a + 300),
(1, 'host_allow_in', '', 'Povolit náběr', 0, @a + 301),
(2, 'host_allow_in', '', '', 0, @a + 301),
(16, 'host_allow_in', '', '', 0, @a + 301),
(1, 'host_ban_out', '', 'Zakázat výplaty', 0, @a + 302),
(2, 'host_ban_out', '', '', 0, @a + 302),
(16, 'host_ban_out', '', '', 0, @a + 302),
(1, 'host_allow_out', '', 'Povolit výplaty', 0, @a + 303),
(2, 'host_allow_out', '', '', 0, @a + 303),
(16, 'host_allow_out', '', '', 0, @a + 303),
(1, 'host_clear_fingerprint', '', 'Vymazat otisk stanice', 0, @a + 304),
(2, 'host_clear_fingerprint', '', '', 0, @a + 304),
(16, 'host_clear_fingerprint', '', '', 0, @a + 304),
(1, 'host_clear_fingerprint_confirm', '', 'Opravdu vymazat otisk této stanice?', 0, @a + 305),
(2, 'host_clear_fingerprint_confirm', '', '', 0, @a + 305),
(16, 'host_clear_fingerprint_confirm', '', '', 0, @a + 305),
(1, 'host_allowed', '', 'Povolen', 0, @a + 306),
(2, 'host_allowed', '', '', 0, @a + 306),
(16, 'host_allowed', '', '', 0, @a + 306),
(1, 'host_banned', '', 'Zakázán', 0, @a + 307),
(2, 'host_banned', '', '', 0, @a + 307),
(16, 'host_banned', '', '', 0, @a + 307),
(1, 'host_allowed_in', '', 'Povolen náběr', 0, @a + 308),
(2, 'host_allowed_in', '', '', 0, @a + 308),
(16, 'host_allowed_in', '', '', 0, @a + 308),
(1, 'host_blocked_in', '', 'Zakázán náběr', 0, @a + 309),
(2, 'host_blocked_in', '', '', 0, @a + 309),
(16, 'host_blocked_in', '', '', 0, @a + 309),
(1, 'host_allowed_out', '', 'Povoleny výplaty', 0, @a + 310),
(2, 'host_allowed_out', '', '', 0, @a + 310),
(16, 'host_allowed_out', '', '', 0, @a + 310),
(1, 'host_blocked_out', '', 'Zakázány výplaty', 0, @a + 311),
(2, 'host_blocked_out', '', '', 0, @a + 311),
(16, 'host_blocked_out', '', '', 0, @a + 311),
(1, 'host_id', '', 'ID stanice', 0, @a + 312),
(2, 'host_id', '', '', 0, @a + 312),
(16, 'host_id', '', '', 0, @a + 312),
(1, 'branch_name', '', 'Název pobočky', 0, @a + 313),
(2, 'branch_name', '', '', 0, @a + 313),
(16, 'branch_name', '', '', 0, @a + 313),
(1, 'Password again', '', 'Heslo znova', 0, @a + 314),
(2, 'Password again', '', '', 0, @a + 314),
(16, 'Password again', '', '', 0, @a + 314),
(1, 'insert_admin', '', 'Založit administrátora', 0, @a + 315),
(2, 'insert_admin', '', '', 0, @a + 315),
(16, 'insert_admin', '', '', 0, @a + 315),
(1, 'admin_profile', '', 'Profil', 0, @a + 316),
(2, 'admin_profile', '', '', 0, @a + 316),
(16, 'admin_profile', '', '', 0, @a + 316),
(1, 'admin_role', '', 'Role', 0, @a + 317),
(2, 'admin_role', '', '', 0, @a + 317),
(16, 'admin_role', '', '', 0, @a + 317),
(1, 'bet_ticket_payout', '', 'Proplatit sázky a tikety', 0, @a + 318),
(2, 'bet_ticket_payout', '', '', 0, @a + 318),
(16, 'bet_ticket_payout', '', '', 0, @a + 318),
(1, 'evaluate_markets', '', 'Vyhodnotit sázky', 0, @a + 319),
(2, 'evaluate_markets', '', '', 0, @a + 319),
(16, 'evaluate_markets', '', '', 0, @a + 319),
(1, 'payout_tickets', '', 'Vyplatit tikety', 0, @a + 320),
(2, 'payout_tickets', '', '', 0, @a + 320),
(16, 'payout_tickets', '', '', 0, @a + 320);
commit;
