start transaction;
set @a=(SELECT MAX(preklad_id) FROM vic_main.preklady);

INSERT INTO vic_main.preklady (`lang_id`, `index_pole`, `short_text`, `text`, `translate`, `preklad_id`) VALUES
(1, 'client_cards', '', 'Klientské karty', 1, @a + 1),
(2, 'client_cards', '', 'Client cards', 1, @a + 1),
(16, 'client_cards', '', '', 1, @a + 1),
(1, 'insert_new_card', '', 'Vložit novou kartu', 1, @a + 2),
(2, 'insert_new_card', '', 'Insert new card', 1, @a + 2),
(16, 'insert_new_card', '', '', 1, @a + 2),
(1, 'fast_assignment_cards_to_branch', '', 'Rychlé přiřazení karet pobočce', 1, @a + 3),
(2, 'fast_assignment_cards_to_branch', '', 'Fast assignment cards to branch', 1, @a + 3),
(16, 'fast_assignment_cards_to_branch', '', '', 1, @a + 3),
(1, 'no_selected_client_cards', '', 'Nevybrány žádné klientské karty', 1, @a + 4),
(2, 'no_selected_client_cards', '', 'No selected client cards', 1, @a + 4),
(16, 'no_selected_client_cards', '', '', 1, @a + 4),
(1, 'client_card_is_used', '', 'Klientská karta je obsazena', 1, @a + 5),
(2, 'client_card_is_used', '', 'Client card is used', 1, @a + 5),
(16, 'client_card_is_used', '', '', 1, @a + 5),
(1, 'no_selected_branch', '', 'Nevybrána pobočka', 1, @a + 6),
(2, 'no_selected_branch', '', 'No selected branch', 1, @a + 6),
(16, 'no_selected_branch', '', '', 1, @a + 6),
(1, 'client_card_branch_binding_ok', '', 'Přiřazení karet proběhlo v pořádku', 1, @a + 7),
(2, 'client_card_branch_binding_ok', '', 'Client card branch binding ok', 1, @a + 7),
(16, 'client_card_branch_binding_ok', '', '', 1, @a + 7),
(1, 'client_card_branch_binding_error', '', 'Přiřazení karet neproběhlo v pořádku', 1, @a + 8),
(2, 'client_card_branch_binding_error', '', 'Client card branch binding error', 1, @a + 8),
(16, 'client_card_branch_binding_error', '', '', 1, @a + 8),
(1, 'close_detail', '', 'Zavřít detail', 1, @a + 9),
(2, 'close_detail', '', 'Close detail', 1, @a + 9),
(16, 'close_detail', '', '', 1, @a + 9),
(1, 'block', '', 'Zablokovat', 1, @a + 10),
(2, 'block', '', 'Block', 1, @a + 10),
(16, 'block', '', '', 1, @a + 10),
(1, 'unblock', '', 'Odblokovat', 1, @a + 11),
(2, 'unblock', '', 'Unblock', 1, @a + 11),
(16, 'unblock', '', '', 1, @a + 11),
(1, 'block_more_cards', '', 'Hromadné zablokování karet', 1, @a + 12),
(2, 'block_more_cards', '', 'Block more cards', 1, @a + 12),
(16, 'block_more_cards', '', '', 1, @a + 12),
(1, 'unblock_more_cards', '', 'Hromadné odblokování karet', 1, @a + 13),
(2, 'unblock_more_cards', '', 'Block more cards', 1, @a + 13),
(16, 'unblock_more_cards', '', '', 1, @a + 13);

commit;
