<?php if ($this->multiple): ?>
<tr>
	<td><input id="allChecker" type="checkbox" onclick="checkAllCombs(this);" /><?=$this->trans('select_all')?></td>
	<td colspan="9"></td>
</tr>
<?php endif; ?>

<?php $i = 0; foreach ($this->layout()->data as $bet) : ++$i; $id = $bet['betId']; ?>
<tr class="noBg">
	<td style="width:60px">
	<?php if ($this->multiple): ?>
		<input type="checkbox" class="checker" id="chkCb_<?= $id ?>" name="chkCb_<?= $id ?>" onclick="useCheckedBets();" value="<?= $id ?>" />
	<?php else: ?>
		<input type="button" onclick="useBet(<?= $id ?>); window.close();" value="&lt;&lt;" />
	<?php endif; ?>
	</td>
	<td class="border-left <?=$bet['alias']?>" style="width:20px" id="bet_id_<?=$i?>"><?=$bet['betId']?></td>
	<td class="border-left" style="width:20px" id="bet_alias_<?=$i?>"><?=$bet['alias']?></td>
	<td class="border-left" id="bet_<?=$i?>"><?=$bet['name']?></td>
	<td class="border-left" id="bet_to_<?=$i?>"><?=It6_Date::fromDb($bet['validToTime'])?></td>
	<td class="border-left" style="width:20px"><?=$this->typesTranslation[$bet['typeId']]?></td>
	<td class="border-left" style="display:none;width:20px" id="bet_parent_<?=$i?>"><?=$bet['parentId']?></td>
</tr>
<?php endforeach; ?>

<input type="hidden" name="opt_par" value="<?=$this->opt_par?>" />
<input type="hidden" name="event_id" value="<?=$this->event_id?>" />
<script type="text/javascript">
	function checkAllCombs(obj) {
		$('input[type="checkbox"][id^="chkCb_"]').attr('checked',obj.checked);
		useCheckedBets();
	}

	function useCheckedBets() {
		var ids = [];
		$('input[id^="chkCb_"]:checked').each(
			function(i, elem) {
				ids.push(elem.value)
			}
		);
		$('#<?= $this->opener ?>', window.opener.document).val(ids.join('; '));
	}

	function useBet(betId) {
		$('#<?= $this->opener ?>', window.opener.document).val(betId);
	}
</script>
