<tbody>
	<?php if (empty($this->layout()->data)): ?>
		<tr><td colspan="12"><?=i18n::tr('no_items')?></td></tr>
	<?php else: ?>
		<?php foreach($this->layout()->data as $row) : ?>
			<tr>
				<td>
					<a href="?section=148&ticketDetail=<?=$row["ticketId"]?>"><?=$row["ticketId"]?></a>
					 (handle: <?=$row["handle"]?>)
				</td>
				<td><?=$row['created']?></td>
				<td>
					<a href="?section=40&user_id=<?=$row["userId"]?>"><?=$row["nick"]?></a>
					 (<?=$row["firstname"]?> <?=$row["lastname"]?> - id: <?=$row["userId"]?>)
				</td>
				<td><?=$row['cash']?></td>
				<td><?=$row['rate']?></td>
				<td><?=$row['win']?></td>
				<td><?=$row['evaluation']?></td>
				<td><?=($row['cancelled'] == '1' ? i18n::tr('ano') : i18n::tr('ne'))?></td>
				<td>
					<input type="submit" name="<?=($row['cancelled'] == '1' ? "allow" : "cancell")?>[<?=$row['ticketId']?>]"
						value="<?=($row['cancelled'] == '1' ? i18n::tr('allow_ticket') : i18n::tr('cancell_ticket'))?>"
						<?php if( $row['cancelled'] != '1' ):?>
							onclick="return confirm('<?=i18n::tr('question_cancell_ticket')?>')"
						<?php else:?>
							onclick="return confirm('<?=i18n::tr('question_allow_ticket')?>')"
						<?php endif;?>
					/>
				</td>
			</tr>
		<?php endforeach?>
	<?php endif; ?>
</tbody>