UPDATE `vic_admin`.`host` SET `branch_id` = '1',
`name` = 'INTERNET',
`is_online` = '1',
`hardware` = NULL ,
`display` = NULL ,
`printer` = NULL ,
`ip` = NULL ,
`win_sn` = NULL ,
`provider_dns` = NULL ,
`provider_gateway` = NULL ,
`provider_ip` = NULL ,
`provider_username` = NULL ,
`provider_password` = NULL ,
`vic_email` = NULL ,
`vic_email_password` = NULL ,
`vic_admin_password` = NULL ,
`vic_employee_password_1` = NULL ,
`vic_employee_password_2` = NULL ,
`note` = NULL WHERE `host`.`id` =1;

