SET foreign_key_checks=0;
start transaction;
truncate vic_admin.parameter;
INSERT INTO vic_admin.`parameter` (`id`, `name`, `value`, `is_host`, `is_branch`, `is_user`, `type`, `mandatory`, `is_admin`, `description`) VALUES
(1, 'branch.clientDeposit', '1', 0, 1, 0, '', 1, 0, 'Zapnutí(0)/vypnutí(1) dotace hráčského konta na pobočce'),
(2, 'branch.clientDepositOnline', '1', 0, 1, 0, '', 1, 0, 'LEGACY'),
(3, 'branch.clientWithdraw', '1', 0, 1, 0, '', 1, 0, 'Zapnutí(0)/vypnutí(1) výběru peněz z hráčského konta na pobočce'),
(4, 'branch.branchDeposit', '1', 0, 1, 0, '', 1, 0, 'Zapnutí(0)/vypnutí(1) dotací pobočky'),
(5, 'branch.branchWithdraw', '1', 0, 1, 0, '', 1, 0, 'Zapnutí(0)/vypnutí(1) odvodů z pobočky'),
(6, 'branch.clientBonusProgram', '1', 0, 1, 0, '', 1, 0, 'Zapnutí(0)/vypnutí(1) věrnostního programu na pobočce'),
(7, 'branch.cashDeskLimit', '10000', 0, 1, 0, '', 1, 0, 'Limit pro odvod z pobočky'),
(12, 'alert.Foo.test', 'jo', 0, 0, 1, NULL, 1, 0, 'Paremetr testovacího alertu, může být smazáno.'),
(13, 'global.adminOff', '0', 0, 0, 0, '', 1, 0, 'TOTAL OVERKILL, DON''T TOUCH!!!!'),
(16, 'alert.to', 'vesely@compbet.com', 0, 1, 1, NULL, 1, 0, 'Emailová adresa na kterou jsou zasílány alerty.'),
(17, 'alert.RateChange.limit', '1', 0, 0, 0, NULL, 1, 0, 'Minimální změna kurzu při které se již posílá alert RateChange.'),
(18, 'alert.TicketCreated.limit', '10', 0, 0, 0, NULL, 1, 0, 'Mimimální vsazená částka při které se posílá alert TicketCreated.'),
(19, 'alert.WinRatio.limit', '2', 0, 0, 0, NULL, 1, 0, 'Minimální výše výhernosti uživatele při které se řadí do alertu výhernost.'),
(20, 'alert.WinRatio.duration', '30', 0, 0, 0, NULL, 1, 0, 'Období za které je braná výhernost uživatele, pro alert výhernost.'),
(22, 'alert.Transaction.limit', '3', 0, 1, 1, NULL, 1, 0, 'Počet transakcí při kterém se pošle alert Transaction.'),
(23, 'alert.Transaction.duration', '10', 0, 1, 1, NULL, 1, 0, 'Časový interval za který se eviduje posílané transakce pro odeslání alertu Transaction.'),
(24, 'rootBetAliasInterval.from', '8000', 0, 0, 0, NULL, 1, 0, 'Dolní limit rozsahu aliasů'),
(25, 'rootBetAliasInterval.to', '9999', 0, 0, 0, NULL, 1, 0, 'Horní limit rozsahu aliasů'),
(26, 'campaign.UserActivation.amount', '100', 0, 0, 0, NULL, 1, 0, 'Počet bodů za aktivaci uživatele.'),
(27, 'campaign.ToMoney.spendRatio', '2', 0, 0, 0, NULL, 1, 0, 'Poměr v kterém se počítá limit pro výměnu bodů za peníze: $amountLimit = $amountOffset + $spendRatio * $point[''balanceSpend''] - $point[''balanceExchange''];'),
(28, 'campaign.ToMoney.amountOffset', '0', 0, 0, 0, NULL, 1, 0, 'Proměná použitá pro výpošet maximálního počtu bodu vyměnitelného za penize: $amountLimit = $amountOffset + $spendRatio * $point[''balanceSpend''] - $point[''balanceExchange''];'),
(29, 'campaign.CreatePointTicket.minAmount', '100', 0, 0, 0, NULL, 1, 0, 'Minimalní počet bodu za které lze vsadit bodový tiket.'),
(30, 'campaign.CreatePointTicket.minCount', '3', 0, 0, 0, NULL, 1, 0, 'Minimální počet příležitostí na bodovém tiketu.'),
(31, 'campaign.CreatePointTicket.minRate', '1.5', 0, 0, 0, NULL, 1, 0, 'Minimální kurz bodového tiketu.'),
(32, 'campaign.CreateMoneyTicket.minAmount', '10', 0, 0, 0, NULL, 1, 0, 'Minimální částka, za kterou uživatel získá body za založení peněžního tiketu.'),
(33, 'campaign.CreateMoneyTicket.minCount', '3', 0, 0, 0, NULL, 1, 0, 'Minimální počet příležitostí na peněžním tiketu za který může získat uživatel bodový bonus.'),
(34, 'campaign.CreateMoneyTicket.minRate', '2.2', 0, 0, 0, NULL, 1, 0, 'Minimální kurz peněžního tiketu za který může uživatel získat bodový bonus.'),
(35, 'campaign.CreateMoneyTicket.pointRatio', '0.1', 0, 0, 0, NULL, 1, 0, 'Poměr bodů které uživatel získá za vsazení tiketu. Body se počítají s potecionální výhry, brány v úvahu jsou pouze ako tikety.'),
(36, 'campaign.CreateMoneyTicket.pointOffset', '0', 0, 0, 0, NULL, 1, 0, 'Minimalni body ziskane za zalozeni penizniho tiketu.'),
(37, 'campaign.PreferenceRate.maxAmount', '500', 0, 0, 0, NULL, 1, 0, 'Maximalní vszené částka, kdy může být uplatněn zvýhodněný kurz.'),
(38, 'campaign.PreferenceRate.minCount', '3', 0, 0, 0, NULL, 1, 0, 'Minimální počet příležitostí na tiketu ana který může být uplatněn zvýhodněný kurz.'),
(39, 'campaign.PreferenceRate.minRate', '7', 0, 0, 0, NULL, 1, 0, 'Minimální kurz tiketu na který může být uplatněn zvýhodněný kurz.'),
(40, 'campaign.PreferenceRate.cost5', '50', 0, 0, 0, NULL, 1, 0, 'Cena za 5% zvyhodněný kurz.'),
(41, 'campaign.PreferenceRate.cost10', '150', 0, 0, 0, NULL, 1, 0, 'Cena za 10% zvyhodněný kurz.'),
(42, 'campaign.PreferenceRate.cost15', '500', 0, 0, 0, NULL, 1, 0, 'Cena za 15% zvyhodněný kurz.'),
(43, 'campaign.BranchVisit.minAmount', '10', 0, 0, 0, NULL, 1, 0, 'Minimalní vsazená částka na tiketu, aby byl brán v úvahu jako návštěva pobočky.'),
(44, 'campaign.BranchVisit.points', '3', 0, 0, 0, NULL, 1, 0, 'Body za navštívení pobočky (udělováno max 1 denně)'),
(45, 'branch.fundReserve', '1000', 0, 1, 0, NULL, 1, 0, 'Min. rezervní částka, která vždy zůstane na pobočce'),
(46, 'branch.minimalDeposit', '200', 0, 1, 0, NULL, 1, 0, 'Minimální dotace pobočky'),
(47, 'branch.minimalWithdraw', '200', 0, 1, 0, NULL, 1, 0, 'Minimální odvod pobočky'),
(48, 'betradar.Bet.InitialStatus', '2', 0, 0, 0, NULL, 1, 0, '2 => suspended, 0=>active'),
(49, 'betradar.Bet.Autoupdate.default', '1', 0, 0, 0, NULL, 1, 0, 'výchozí stav aktualizování kurzu z betradaru'),
(50, 'betradar.Bet.BookmakerId', '1', 0, 0, 0, NULL, 1, 0, 'autor sazky ktera prijde z betradaru'),
(51, 'betradar.Email.OnError', '1', 0, 0, 0, NULL, 1, 0, 'posilat maily pri chybach'),
(52, 'betradar.Email.Always', '0', 0, 0, 0, NULL, 1, 0, 'posilat email pri kazdem importu'),
(53, 'host.ban-all', '0', 0, 0, 0, NULL, 1, 0, 'Aktivace(0)/deaktivace(1) všech hostů v systému'),
(54, 'pagination.Bet.count', '20', 0, 0, 0, NULL, 1, 1, 'počet záznamů na stránce obrazovka sázek'),
(55, 'host.ban-all-out', '0', 0, 0, 0, NULL, 1, 0, 'Vypnutí(0)/zapnutí(1) výběrů všech hostů v systému'),
(57, 'pagination.Ticket.count', '20', 0, 0, 0, NULL, 1, 1, 'Pokud je nenulový jsou zakázány všechny transakce navyšující zůstatek pobočky.'),
(58, 'pagination.PointTransaction.count', '20', 0, 0, 1, NULL, 1, 0, 'Pokud je nenulový jsou zakázány všechny transakce ponižující zůstatek pobočky.'),
(59, 'pagination.Transaction.count', '20', 0, 0, 1, NULL, 1, 0, 'počet záznamů na stránce transakce'),
(60, 'confirmation.ticketSimple.lowerTreshold.stake', '21', 0, 0, 1, NULL, 1, 0, 'Částka, nad kterou jde simple tiket vždy do schvalovačky'),
(61, 'confirmation.ticketCombi.lowerTreshold.stake', '41', 0, 0, 1, NULL, 1, 0, 'Částka, nad kterou jde kombi/maxikombi tiket vždy do schvalovačky.'),
(62, 'branch.Advert.ticketHeader', 'toto je globalni reklamni text na tiketu', 0, 1, 0, '', 1, 0, 'reklamní text na tiketu'),
(63, 'validation.ticket.minimal.stake', '10', 0, 0, 0, '', 1, 0, 'Minimální vklad na tiket v centrální měně'),
(64, 'validation.ticket.maximal.stake', '33333', 0, 0, 0, '', 1, 0, 'Maximální vklad na tiket v centrální měně'),
(65, 'pagination.Event.count', '20', 0, 0, 0, NULL, 1, 1, 'Počet záznamů na stránce turnaj/událost'),
(68, 'validation.ticket.maximal.win', '1000000', 0, 1, 1, '''''', 1, 0, 'Maximální čistá výhra na tiket (u maxikombinátoru na podtiket)'),
(70, 'alert.BranchBlackList.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu BranchBlackList'),
(71, 'alert.BranchTicketsCount.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu BranchTicketsCount'),
(72, 'alert.CanceledTickets.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu CanceledTickets'),
(73, 'alert.HostDeposits.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu HostDeposits'),
(74, 'alert.MailAbstract.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu MailAbstract'),
(75, 'alert.NewUsers.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu NewUsers'),
(76, 'alert.TicketCreated.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu TicketCreated'),
(77, 'alert.Transaction.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu Transaction'),
(78, 'alert.UserBlacklist.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu UserBlacklist'),
(79, 'alert.WinRatio.disabled', '0', 0, 0, 0, NULL, 1, 0, 'Zakázání alertu Winratio'),
(80, 'duplicate.Ticket.count', '4', 1, 1, 1, '', 1, 1, 'Maximální počet stejných tiketů za 24 hod');
commit;
SET foreign_key_checks=1;
