<?php
$i=0;
$aBetIds = array();
reset($this->Adata['date']);
$firstKey = key($this->Adata['date']);

if(!empty($firstKey)) : //echo $firstKey."</br>"; ?>
          <div class="contentbox no-padding">
            <table class="table table-striped table-hover matches xxx">
              <thead>
                <tr>
                  <th>Čas</th>
                  <th><?=$this->Adata['text']?> <?=$this->Adata['textNote']?></th>
  	       		  <?php foreach($this->Adata['sloupec'] as $dataSlName) { ?>
				  <th class="text-center"><?=$this->escape($dataSlName); ?></th>
				  <?php } ?>

                  <th colspan="2"></th>
                </tr>
              </thead>

              <tbody>
	
		<?php foreach($this->Adata['date'] as $datum=>$dataDate):
		?>
			<?php foreach($dataDate as $bet_id=>$dataOdds):
				$array_diff = array_diff_key($this->Adata['sloupec'], $dataOdds['sloupec']);
				foreach ($array_diff as $key => $value) {
					$array_diff[$key] = 1;
				}
				$dataOdds['sloupec'] = $dataOdds['sloupec'] + $array_diff;
				ksort($dataOdds['sloupec']);
				
				$betradar_match_id = $dataOdds["betradar_match_id"];

				// dočasné řešení
				$betDate = strtotime(date("d.m.Y H:i:s", strtotime(date("d",strtotime($datum)).".".date("m",strtotime($datum)).".".date("Y",strtotime($datum))." ".$dataOdds['hour'])));
				if ( $betDate < time() ) {
					//continue;
				}
				?>

				<tr id="<?= $bet_id ?>">
                  <td class="match-date"><?= substr($datum, 0, -4); ?> <br> <?=$dataOdds['hour']; ?></td>
                  <td class="match-icos">
                    <strong><?= $this->escape($dataOdds['text']) ?></strong>
						<?php if(!empty($dataOdds['liveBetId'])) { ?>
							<a class="ico-self ico-tv" title="<?=$this->trans('available_as_live')?>" data-toggle="tooltip" data-placement="top"
							   href="<?=It6_Models_Livebetting::getUrl($dataOdds['liveBetId'], true, false)?>">L</a>
						<?php } else { ?>
							<span class="liveInfoAkoSpace">&nbsp;</span>
						<?php } ?>
						<?php if(mb_strlen($dataOdds['info']) > 0) { ?>
							<span class="ico-self ico-info" title="<?=$this->escape($dataOdds['info']); ?>" data-toggle="tooltip" data-placement="top"></span>
						<?php } else { ?>
							<span class="liveInfoAkoSpace">&nbsp;</span>
						<?php } ?>
						<?php if($dataOdds['ako']) { ?>
							<span class="betOfferTableInfo1 liveInfoAko1 tooltip1" title="<?=$this->escape($dataOdds['ako']); ?>AKO"><?=$this->escape($dataOdds['ako']); ?>!</span>
						<?php } else { ?>
							<span class="liveInfoAkoSpace1">&nbsp;</span>
						<?php } ?>
                  </td>

					<?php foreach ($dataOdds['sloupec'] as $sloupec_id => $odds): ++$i; ?>
						<td id="b<?=$bet_id; ?>c<?=$sloupec_id; ?>" class="odds" >
							<?php if($odds != 1) { ?>
								<a
									class=""
									href="javascript:void(0);"
									onclick="ticketUpdate(<?=$bet_id .','. $sloupec_id .',\''. $this->EscapeJs($dataOdds['text'], true, true) .'\',\''. $this->EscapeJs($this->Adata['fullText'], true, true) .'\',\''. $this->Adata['sloupec'][$sloupec_id] .'\',null,'.  $dataOdds['simple']; ?>);"
								>
									<?=$odds?>
								</a>
							<?php } else { ?>
								-
							<?php } ?>
						</td>
					<?php endforeach?>

                  <td class="text-center"><a href="#" class="ico-self ico-stats" title="Statistiky" data-toggle="tooltip" data-placement="top"></a></td>

				  <td class="text-right">
						<?php $isPlus = intval($dataOdds['plus']) > 0 && !$this->isDetailView; ?>
						<?php if($isPlus): ?>
							<a href="javascript:getBetDetails('<?=$this->UrlSet(9,$this->seoUrl($dataOdds['text']) . '-m'. $bet_id .'/'); ?>',<?=$bet_id?>)" class="more-bets" title="Více sázek" data-toggle="tooltip" data-placement="top">
								<span id="plusMinus<?=$bet_id?>">+</span><?=$dataOdds['plus']; ?>
							</a>
						<?php endif; ?>
					</td>
                </tr>
   				<?php if ($isPlus) { $cellCount = 8 + count($dataOdds['sloupec']); ?>
					<tr class="more-bets-content" id="bet_details_tr_<?=$bet_id?>" style="display:none">
						<td class="bet_detail" colspan="<?= $cellCount ?>">
							<div id="bet_details_<?=$bet_id?>"></div>
						</td>
					</tr>
				<?php } ?>
			<?php endforeach?>
		<?php endforeach?>
		</tbody>
      </table>
    </div>
<?php endif; ?>