<?php
//echo "<pre>";
//print_r($this->Adata['date']);
?>
<?php $first = true; foreach($this->Adata['date'] as $datum=>$dataDate): ?>
	<?php foreach($dataDate as $bet_id=>$dataOdds):
		$dataOddsCount = count($dataOdds['sloupec']);
		$sl_pocet = ceil($dataOddsCount/$this->Adata['sloupec_pocet_max']);
		$linesCount = ceil(($dataOddsCount) / $sl_pocet);
		$fillingCellsCount = ($sl_pocet - ($dataOddsCount % $sl_pocet)) % $sl_pocet;
	?>
		<table class="betOfferTable<?= (!$this->firstTable) ? '' : ' first'?>">
			<?php if ($first) : $first = false; ?>
				<thead>
					<tr>
						<?php if($this->isDetailView): ?>
							<th class="alias borderRight"></th>
						<?php endif; ?>
						<th class="aliasAndName" colspan="<?= $this->isDetailView ? '4' : '5'; ?>">
							<span><?=$this->Adata['text']; ?></span>			
						</th>
					</tr>
				</thead>
			<?php endif?>
			<tbody>
				<tr>
					<td class="alias borderRight">
						<?=(!empty($dataOdds['alias_new'])) ? $dataOdds['alias_new'] : $dataOdds['alias']?>
					</td>

					<td class="name borderLeft">
						<span class="name"><?= $this->escape($dataOdds['text']) ?></span>
						<div class="clear"></div>
						<span class="datetimeNarrower"><?= substr($datum, 0, -4); ?> | <?=$dataOdds['hour']; ?></span>
						<?php //if (!empty($dataOdds['betradar_match_id'])) : ?>
							<!-- <a
								onclick="window.open(this.href,'_blank');return false;"
								href="<?//=BETRADAR_STATS_URL?>&amp;matchid=<?//=$dataOdds['betradar_match_id']?>"
								class="statsNarrower"
							>
								<img src="/images/graph-crop.png" alt="<?//=$this->trans('stats'); ?>" title="<?//=$this->trans('stats'); ?>" />
							</a> -->
						<?php //endif; ?>
					</td>

					<td class="datetime datetimeB borderLeft borderRight">
						<?= substr($datum, 0, -4); ?> | <?=$dataOdds['hour']; ?>
					</td>
					
					<?php $isPlus = intval($dataOdds['plus']) > 0 && !$this->isDetailView; ?>
					<td class="plus borderLeft borderRight">
						<?php if ($isPlus) : ?>
							<a href="<?=$this->UrlSet(9,$this->seoUrl($dataOdds['text']) . '-m'. $bet_id .'/'); ?>">
								+<?=$dataOdds['plus']; ?>
							</a>
						<?	endif;	?>
					</td>
					<td class="stats borderLeft">
						<!-- <div>
							<?php //if (!empty($dataOdds['betradar_match_id'])) : ?>
								<a
									onclick="window.open(this.href,'_blank');return false;"
									href="<?//=BETRADAR_STATS_URL?>&amp;matchid=<?//=$dataOdds['betradar_match_id']?>"
								>
									<img src="/images/graph_smaller_without_bck.png" alt="<?//=$this->trans('stats'); ?>" title="<?//=$this->trans('stats'); ?>" />
								</a>
							<?php //endif?>
						</div> -->
					</td>
				</tr>
			</tbody>
		</table>
		<table class="betOfferTable betOfferTypeResultsTable" cellspacing="0">
			<tbody>
				<?php $sl_help = 0?>
				<?php $sl_last = true; $first = true; $currentLine = 1; $currentCell = 0; ?>				
				<?php foreach($dataOdds['sloupec'] as $sl_id=>$odds) : $currentCell++; ?>
				
					<?php if ($sl_last) : ?>
						<tr<?=$first?' class="first"':''?>>
							<td class="alias borderRight"></td>
							<td class="leftPaddingCols<?= $sl_pocet ?> borderLeft"></td>
					<?php endif?>
							
					<?php $sl_last = (0 == ++$sl_help % $sl_pocet)
							|| $currentCell === $dataOddsCount?>
							
					<td class="resultB">
						<strong><?=$this->escape($this->Adata['sloupec'][$sl_id]); ?></strong>
					</td>
					<td id="b<?=$bet_id?>c<?=$sl_id?>" class="rateB">
						<?php if($odds != 1) : ?>
							<a
								class="kurz"
								href="javascript:void(0);"
								onclick="ticketUpdate(<?=$bet_id .','. $sl_id .',\''. $this->EscapeJs($dataOdds['text'], true, true) .'\',\''. $this->EscapeJs($this->Adata['fullText'], true, true) .'\',\''. $this->Adata['sloupec'][$sl_id] .'\',null,'.	$dataOdds['simple']; ?>);"
							>
								<?=$odds?>
							</a>
						<?php else : ?>
							-
						<?php endif?>
					</td>
					
					<?php if ($sl_last) :
					if ($currentLine == $linesCount) :
						for ($i = 0; $i < $fillingCellsCount; $i++) :
							?><td class="resultB"></td><td class="rateB"></td><?
						endfor;
					endif;
					$currentLine++;
					?>
					<td class="datetime datetimeB borderLeft borderRight"></td>
					<td class="plus borderLeft borderRight"></td>
					<td class="stats borderLeft"></td>
					</tr>
					<?php endif?>
				<?php $first = false; endforeach?>
			</tbody>
		</table>
	<?php endforeach; ?>
<?php endforeach; ?>