  <table class="table-filter">
    <tr><td>
    <?=I18n::tr('Search')?>
      <form method="get" action="">
        <input
          type="text"
          name="search"
          value="<?=isset($_REQUEST['search']) ? $_REQUEST['search'] : ''?>" />
        <input type="submit" value="<?=I18n::tr('Search')?>" />
        <input type="hidden" name="node" value="<?=isset($_REQUEST['node']) ? $_REQUEST['node'] : ''?>" />
      </form>
    </td></tr>
  </table>

  <div>
	  <?php
	  $getParams = '';
	  foreach ($_GET as $key => $value) {
		  if ($key !== 'gmenu') {
			  $getParams .= "&$key=$value";
		  }
	  }
	  ?>	  
    <a
      href="?section=<?=$this->section . $getParams ?>"
      <?php if(!isset($_REQUEST['gmenu']) || $_REQUEST['gmenu'] == 'all'):?>
        style="font-weight: bold;"
      <?php endif?>
    >
      <?=I18n::tr('Show all')?>
    </a>


    <?php foreach($menuItems as $item):?>
      &nbsp;|
      <!--<input
				type="checkbox"
				class="no"
				name="galery_menu[<?=$item['galerie_menu_id']?>]"
			/>-->
			<a
				href="?section=<?=$this->section?>&gmenu=<?=$item['galerie_menu_id'] . $getParams ?>"
        <?php if(isset($_REQUEST['gmenu']) && $_REQUEST['gmenu'] == $item['galerie_menu_id']):?>
          style="font-weight: bold;"
        <?php endif?>
      >
        <?=Help::Html($item['nazev'])?>
      </a>
		<!--	<a href="?section=<?=$this->section?>&gmenud=<?=$item['galerie_menu_id']?>&search=<?=$_REQUEST['search']?>">
				x
			</a>-->
    <?php endforeach?>
  </div>



  

  <table class="table-detail width-100" >
  <tr><th colspan="3"><?=I18n::tr('Images')?></th></tr>
    <?php foreach($images as $image):?>
      <tr>
        <td>
          <a href="<?=$image['pathFullSize']?>" target="_blank">
            <img src="<?=$image['path']?>" class="img" />
          </a>
        </td>

        <td>
          <div>
            <label><?=I18n::tr('File Name')?>:</label>
            <?=Help::Html($image['name'])?>
          </div>

          <div>
            <label><?=I18n::tr('Image Description')?>:</label>
            <?=Help::Html($image['popis'])?>
          <div>

          <div>
            <label><?=I18n::tr('Alt Text')?>:</label>

            <?php foreach($image['alt'] as $k => $v):?>
              <div>
                &nbsp;
                <label><?=$k?>:</label>
                <?=Help::Html($v)?>
              </div>
            <?php endforeach?>
        </td>

        <td>
          <button
            class="sinput"
            name="insertImage[<?=$image['imageId']?>]"
            onClick="insertImage({'name':'<?=$image['name']?>', 'id':'<?=$image['imageId']?>', 'alt':{<?php foreach($image['alt'] as $k => $v){echo "'".$k."':'".$v."',";}?>}})"
          >
			<?=I18n::tr('Insert')?>
		  </button>
        </td>
      </tr>
    <?php endforeach?>

  </table>