<div id="superhp">
  <div class="content">
    <h3>Účet je již aktivován na pobočce, nebyly však ještě vloženy žádné finanční prostředky na Váš účet.</h3>
  </div>
</div>
<div id="rcol" class="column240">
  <div class="box-kroky box-registartion-right">
    <div class="head">
      <h2><?=$this->trans('reg_steps'); ?></h2>
    </div>
    <div class="content">
      <a class="krok">
          <span class="poradi"><strong>1</strong></span>
          <span class="nazev"><?=$this->trans('register_reg'); ?></span>
      </a>
      <a class="krok">
          <span class="poradi"><strong>2</strong></span>
          <span class="nazev"><?=$this->trans('register_nextstep'); ?></span>
      </a>
      <a class="krok">
          <span class="poradi"><strong>3</strong></span>
          <span class="nazev"><?=$this->trans('register_active'); ?></span>
      </a>
      <a class="krok krok-sel">
          <span class="poradi"><strong>4</strong></span>
          <span class="nazev"><?=$this->trans('register_deposit'); ?></span>
      </a>
      <a class="krok">
          <span class="poradi"><strong>5</strong></span>
          <span class="nazev"><?=$this->trans('register_play'); ?></span>
      </a>        
    </div>
    <div class="cb"></div>
  </div>
</div>
