<!-- Google Code for Registrace Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1010838218;
var google_conversion_language = "cs";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "nbV_CK6uzAIQytWA4gM";
var google_conversion_value = 0;
if (50) {
  google_conversion_value = 50;
}
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js"> [^]
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/1010838218/?value=50&label=nbV_CK6uzAIQytWA4gM&guid=ON&script=0"/> [^]
</div>
</noscript> 