<div class="m0a w50p">
	<img src="/new/images/logo.png" alt="logo" />
	<h2 class="boxheader"><?= $this->trans('live-login') ?></h2>	
	<div class="contentbox">
		
		<?php if ($this->trans('live-login-text') !== 'live-login-text') { ?>
			<p><?= $this->trans('live-login-text'); ?></p>
		<?php } ?>
		<?php if (true === $this->authenticated): ?>
          <p>
            <a href="<?= $this->redirectUrl ?>"><?= $this->redirectUrl ?></a>
          </p>
        <?php else: ?>
          <?php if (false === $this->authenticated): ?>
            <?= It6_FeedbackMsg::printError($this->errMsg) ?>
          <?php endif; ?>
        <form method="post" action="" id="loginForm">
			<table class="table form-table">
				<tr>
					<td class="col-xs-4"><label for="nick"><?= $this->trans('reg_email') ?>:</label></td>
					<td><input type="text" id="nick" name="nick" placeholder="<?= $this->trans('reg_email') ?>" /></td>
				</tr>
				<tr>
					<td class="col-xs-4"><label for="pass"><?= $this->trans('reg_pass') ?>:</label></td>
					<td> <input type="password" id="pass" name="pass" placeholder="<?= $this->trans('reg_pass') ?>" /></td>
				</tr>
				<tr>
					<td colspan="2" class="text-center">
						<input type="submit" value="<?= $this->trans('login') ?>" id="login" class="btn btn-biggest" />
						<br><a class="" href="<?=$this->UrlSet(25); ?>">
							<?=$this->trans('forget_pass');?>
						</a>
					</td>
				</tr>
			</table>
			<?php if (!empty($this->matchId)): ?>
            <input type="hidden" name="matchId" value="<?= $this->matchId ?>" />
            <?php endif; ?>
            <input type="hidden" name="lang_id" value="<?= $this->lang_id ?>" />
            <input type="hidden" name="live" value="1" />
        </form>
        <?php endif; ?>
	</div>
</div>